const UI_TEXT = {
    ko: {
        enterAgent: "Enter Agent",
        accessRequired: "접근 코드를 입력해 주세요.",
        accessPlaceholder: "접근 코드 입력",
        accessHelper: "접근 코드는 서버에서 확인되며, 승인되면 바로 다음 단계로 이어집니다.",
        accessVerifying: "접근 코드를 확인하고 있습니다.",
        accessInvalid: "유효하지 않은 접근 코드입니다.",
        accessInvalidRemaining: "유효하지 않은 접근 코드입니다. 남은 시도 {count}회.",
        accessLocked: "실패 횟수가 많아 잠시 잠겼습니다. 잠시 후 다시 시도해 주세요.",
        accessLockedWithTime: "실패 횟수가 많아 잠시 잠겼습니다. {time} 후에 다시 시도해 주세요.",
        accessLockedNewWindow: "3회 연속 실패로 이 창은 잠겼습니다. {time} 후 다시 시도하거나 새 창에서 다시 시작해 주세요.",
        accessUnavailable: "접근 코드 검증 서버에 연결할 수 없습니다.",
        accessGranted: "접근이 확인되었습니다. 가이드를 여는 중입니다.",
        accessShow: "보기",
        accessHide: "숨기기",
        logout: "로그아웃",
        loggedOut: "세션이 종료되었습니다. 다시 접근 코드를 입력해 주세요.",
        guideTitle: "사용 방법을 아시나요?",
        guideQuick: "Quick Guide",
        guideLine1: "질문은 한 번에 하나씩 열립니다.",
        guideLine2: "답변을 마칠 때마다 다음 방향을 넓혀주는 힌트가 제공됩니다.",
        guideLine3: "네 단계를 마치면 바로 활용 가능한 시나리오가 정리됩니다.",
        startAfterGuide: "좋아요. 이제 Q1부터 한 단계씩 진행할게요. 각 답변 뒤에 다음 방향을 더 선명하게 만드는 힌트를 함께 보여드립니다.",
        unlockedPlaceholder: "사용 방법 확인 후 Q1부터 차례대로 시작합니다.",
        stateMissing: "질문에 답하면 현재 선택한 내용이 여기에 정리됩니다.",
        checkPlaceholder: "시나리오를 생성하면 구성 점검 결과가 표시됩니다.",
        outputPlaceholder: "접근 확인 후 네 가지 질문을 순서대로 완료하면 상세 시나리오와 역할별 활용안을 확인할 수 있습니다.",
        progress1: "Q1 담당 업무",
        progress2: "Q2 지역",
        progress3: "Q3 타겟 고객 및 상황",
        progress4: "Q4 반영 기기",
        prev: "이전",
        next: "다음",
        build: "Scenario Build",
        downloadMarkdown: "Download Markdown",
        downloadJson: "Download JSON",
        printPdf: "Print / Save PDF",
        copySummary: "Copy Summary",
        current: "입력 요약",
        check: "구성 점검",
        output: "Scenario Output",
        roleQuestion: "Q1. 어떤 관점에서 시나리오를 만들고 싶나요?",
        countryQuestion: "Q2. 어느 국가를 대상으로 하나요?",
        personaQuestion: "Q3. 타겟의 생활 맥락을 잡아 주세요",
        deviceQuestion: "Q4. 어떤 기기를 중심으로 구성할까요?",
        purposePlaceholder: "예: 맞벌이 가정이 퇴근 후 아이와 함께 집에 들어왔을 때 더 빠르고 편안하게 저녁 시간을 시작하고 싶다",
        countryHelper: "국가와 지역을 고르면 어떤 생활 장면이 더 설득력 있게 읽히는지 바로 좁혀집니다.",
        personaHelper: "가구 유형과 생활 맥락을 함께 고르면 타겟이 더 선명해지고, 시나리오 톤도 달라집니다.",
        deviceHelper: "상위 카테고리를 먼저 고르고 필요한 기기만 남기면 실제 사용 장면이 훨씬 빠르게 잡힙니다.",
        roleMissing: "Q1에서 담당 업무 관점을 먼저 선택해 주세요.",
        countryMissing: "Q2에서 국가를 선택해 주세요.",
        personaMissing: "Q3에서 타겟 세그먼트를 선택하거나 상황 설명을 입력해 주세요.",
        allMissing: "네 가지 질문을 모두 완료한 뒤 다시 시도해 주세요.",
        downloadFirst: "먼저 시나리오를 생성해 주세요.",
        summaryState: "Input Summary",
        detailedScenario: "상세 시나리오",
        automation: "자동화 흐름",
        facts: "구성 근거",
        confirmed: "확정 정보",
        assumptions: "참고 메모",
        lenses: "활용 관점",
        effects: "기대 효과",
        segment: "추천 사용자",
        guide: "시작 가이드",
        evaluation: "활용 판단",
        why: "Why",
        comparison: "Comparison",
        note: "Note",
        roleLens: "Role Lens",
        executionPoints: "실행 포인트",
        summary: "요약",
        fit: "적합",
        review: "재검토 필요",
        fitCheck: "구성 적합성",
        availabilityCheck: "기기 가용성",
        executionCheck: "실행 가능성",
        clarityCheck: "메시지 명확성",
        metricCheck: "성과 연결성"
    },
    en: {
        enterAgent: "Enter Agent",
        accessRequired: "Please enter the access code.",
        accessPlaceholder: "Enter access code",
        accessHelper: "The access code is verified on the server and creates a session on success.",
        accessVerifying: "Verifying your access code.",
        accessInvalid: "Invalid access code.",
        accessInvalidRemaining: "Invalid access code. {count} attempts remaining.",
        accessLocked: "Too many failed attempts. Try again later.",
        accessLockedWithTime: "Too many failed attempts. Try again in {time}.",
        accessLockedNewWindow: "This tab is locked after 3 failed attempts. Try again in {time}, or start again in a new tab.",
        accessUnavailable: "The access verification server is unavailable.",
        accessGranted: "Access confirmed. Opening the guide.",
        accessShow: "Show",
        accessHide: "Hide",
        logout: "Logout",
        loggedOut: "Your session has been signed out. Enter the access code again.",
        guideTitle: "Do you know how to use this agent?",
        guideQuick: "Quick Guide",
        guideLine1: "Questions appear one at a time.",
        guideLine2: "After each answer, you get a short prompt that expands the next direction.",
        guideLine3: "Once all four steps are complete, a practical scenario is generated immediately.",
        startAfterGuide: "Good. We will start from Q1 step by step, with a short prompt after each answer to sharpen the next direction.",
        unlockedPlaceholder: "After the usage check, you will start from Q1 in sequence.",
        stateMissing: "Your current selections will appear here as you answer each question.",
        checkPlaceholder: "A quick structure check will appear after the scenario is generated.",
        outputPlaceholder: "After access confirmation and all four questions, you will see the detailed scenario and role-based applications.",
        progress1: "Q1 Work Lens",
        progress2: "Q2 Region",
        progress3: "Q3 User & Context",
        progress4: "Q4 Device",
        prev: "Back",
        next: "Next",
        build: "Scenario Build",
        downloadMarkdown: "Download Markdown",
        downloadJson: "Download JSON",
        printPdf: "Print / Save PDF",
        copySummary: "Copy Summary",
        current: "Current Input",
        check: "Structure Check",
        output: "Scenario Output",
        roleQuestion: "Q1. From which professional lens do you want to build this scenario?",
        countryQuestion: "Q2. Which country is this for?",
        personaQuestion: "Q3. Define the target's living context",
        deviceQuestion: "Q4. Which device should anchor the scenario?",
        purposePlaceholder: "Example: A dual-income family wants to start the evening faster and more comfortably right after arriving home with their child.",
        countryHelper: "Pick the market and region first to narrow which life moment will feel most convincing.",
        personaHelper: "Combine household type and living context to make the target sharper and the scenario tone more specific.",
        deviceHelper: "Start with a top category, then trim the device list to the exact mix you want to frame.",
        roleMissing: "Please choose the work lens first in Q1.",
        countryMissing: "Please choose the country in Q2.",
        personaMissing: "In Q3, choose the target segment or describe the situation.",
        allMissing: "Please complete all four questions before generating the scenario.",
        downloadFirst: "Please generate a scenario first.",
        summaryState: "Input Summary",
        detailedScenario: "Detailed Scenario",
        automation: "Automation Flow",
        facts: "Scenario Basis",
        confirmed: "Confirmed Info",
        assumptions: "Notes",
        lenses: "Use Cases by Role",
        effects: "Expected Impact",
        segment: "Recommended Audience",
        guide: "Getting Started",
        evaluation: "Evaluation",
        why: "Why",
        comparison: "Comparison",
        note: "Note",
        roleLens: "Role Lens",
        executionPoints: "Execution Points",
        summary: "Summary",
        fit: "Good",
        review: "Needs Review",
        fitCheck: "Scenario Fit",
        availabilityCheck: "Device Availability",
        executionCheck: "Execution Feasibility",
        clarityCheck: "Message Clarity",
        metricCheck: "Outcome Linkage"
    },
    de: {
        enterAgent: "Agent Starten",
        accessRequired: "Bitte geben Sie den Zugangscode ein.",
        accessPlaceholder: "Zugangscode eingeben",
        accessHelper: "Der Zugangscode wird serverseitig geprüft und erzeugt bei Erfolg eine Sitzung.",
        accessVerifying: "Der Zugangscode wird geprüft.",
        accessInvalid: "Der Zugangscode ist ungültig.",
        accessInvalidRemaining: "Der Zugangscode ist ungültig. Verbleibende Versuche: {count}.",
        accessLocked: "Zu viele Fehlversuche. Bitte versuchen Sie es später erneut.",
        accessLockedWithTime: "Zu viele Fehlversuche. Bitte versuchen Sie es in {time} erneut.",
        accessLockedNewWindow: "Dieser Tab ist nach 3 Fehlversuchen gesperrt. Versuchen Sie es in {time} erneut oder starten Sie in einem neuen Tab.",
        accessUnavailable: "Der Verifizierungsserver ist nicht erreichbar.",
        accessGranted: "Zugang bestätigt. Die Anleitung wird geöffnet.",
        accessShow: "Anzeigen",
        accessHide: "Ausblenden",
        logout: "Abmelden",
        loggedOut: "Ihre Sitzung wurde beendet. Bitte geben Sie den Zugangscode erneut ein.",
        guideTitle: "Kennen Sie die Nutzung dieses Agents?",
        guideQuick: "Kurzanleitung",
        guideLine1: "Die Fragen erscheinen nacheinander.",
        guideLine2: "Nach jeder Antwort erhalten Sie einen kurzen Hinweis für die nächste Richtung.",
        guideLine3: "Nach vier Schritten wird sofort ein nutzbares Szenario erstellt.",
        startAfterGuide: "Gut. Wir starten jetzt Schritt für Schritt mit Q1 und geben nach jeder Antwort einen kurzen Hinweis für die nächste Richtung.",
        unlockedPlaceholder: "Nach der kurzen Nutzungsabfrage starten Sie nacheinander mit Q1.",
        stateMissing: "Ihre aktuellen Eingaben werden hier während der Fragen zusammengefasst.",
        checkPlaceholder: "Nach der Generierung erscheint hier eine kurze Strukturprüfung.",
        outputPlaceholder: "Nach Zugang und vier Fragen sehen Sie das detaillierte Szenario und die rollenspezifischen Nutzungsideen.",
        progress1: "Q1 Perspektive",
        progress2: "Q2 Region",
        progress3: "Q3 Nutzer & Kontext",
        progress4: "Q4 Gerät",
        prev: "Zurück",
        next: "Weiter",
        build: "Szenario Erstellen",
        downloadMarkdown: "Markdown Laden",
        downloadJson: "JSON Laden",
        printPdf: "Drucken / PDF Speichern",
        copySummary: "Zusammenfassung Kopieren",
        current: "Aktuelle Eingabe",
        check: "Strukturprüfung",
        output: "Szenario-Ausgabe",
        roleQuestion: "Q1. Aus welcher fachlichen Perspektive möchten Sie dieses Szenario erstellen?",
        countryQuestion: "Q2. Für welches Land ist das Szenario gedacht?",
        personaQuestion: "Q3. Welchen Nutzertyp und welche Situation haben Sie im Kopf?",
        deviceQuestion: "Q4. Welches Gerät soll im Zentrum stehen?",
        purposePlaceholder: "Beispiel: Eine Doppelverdiener-Familie möchte den Abend nach der Rückkehr mit ihrem Kind schneller und angenehmer beginnen.",
        countryHelper: "Wählen Sie zuerst Markt und Region, damit klarer wird, welcher Alltagsmoment am stärksten wirkt.",
        personaHelper: "Kombinieren Sie Haushaltstyp und Lebenskontext, damit Zielgruppe und Szenarioton präziser werden.",
        deviceHelper: "Starten Sie mit einer Oberkategorie und grenzen Sie dann die konkrete Gerätekombination ein.",
        roleMissing: "Bitte wählen Sie zuerst in Q1 die fachliche Perspektive aus.",
        countryMissing: "Bitte wählen Sie in Q2 das Land aus.",
        personaMissing: "Wählen Sie in Q3 den Nutzertyp oder beschreiben Sie die Situation.",
        allMissing: "Bitte beantworten Sie zuerst alle vier Fragen.",
        downloadFirst: "Bitte erzeugen Sie zuerst ein Szenario.",
        summaryState: "Eingabeübersicht",
        detailedScenario: "Detailliertes Szenario",
        automation: "Automationsablauf",
        facts: "Grundlage des Szenarios",
        confirmed: "Bestätigte Informationen",
        assumptions: "Hinweise",
        lenses: "Nutzung nach Rolle",
        effects: "Erwartete Wirkung",
        segment: "Empfohlene Zielgruppe",
        guide: "Erste Schritte",
        evaluation: "Bewertung",
        why: "Warum",
        comparison: "Vergleich",
        note: "Hinweis",
        roleLens: "Rollenansicht",
        executionPoints: "Umsetzungspunkte",
        summary: "Zusammenfassung",
        fit: "Passend",
        review: "Überprüfen",
        fitCheck: "Szenario-Fit",
        availabilityCheck: "Geräteverfügbarkeit",
        executionCheck: "Umsetzbarkeit",
        clarityCheck: "Botschaftsklarheit",
        metricCheck: "Wirkungsbezug"
    },
    fr: {
        enterAgent: "Entrer dans l'agent",
        accessRequired: "Veuillez saisir le code d'accès.",
        accessPlaceholder: "Saisir le code d'accès",
        accessHelper: "Le code d'accès est vérifié sur le serveur et ouvre immédiatement l'étape suivante après validation.",
        guideTitle: "Savez-vous comment utiliser cet agent ?",
        guideQuick: "Guide Rapide",
        guideLine1: "Les questions apparaissent une par une.",
        guideLine2: "Après chaque réponse, vous recevez un court indice pour orienter la suite.",
        guideLine3: "Une fois les quatre étapes terminées, un scénario exploitable est généré immédiatement.",
        startAfterGuide: "Très bien. Nous allons commencer à partir de la Q1, étape par étape, avec un court indice après chaque réponse.",
        unlockedPlaceholder: "Après cette vérification rapide, vous commencerez à partir de la Q1.",
        stateMissing: "Vos sélections actuelles apparaîtront ici au fur et à mesure.",
        checkPlaceholder: "Une vérification rapide de la structure apparaîtra après la génération du scénario.",
        outputPlaceholder: "Après l'accès et les quatre questions, vous verrez le scénario détaillé et les applications par rôle.",
        progress1: "Q1 Rôle",
        progress2: "Q2 Région",
        progress3: "Q3 Utilisateur et contexte",
        progress4: "Q4 Appareil",
        prev: "Précédent",
        next: "Suivant",
        build: "Créer le scénario",
        downloadMarkdown: "Télécharger Markdown",
        downloadJson: "Télécharger JSON",
        printPdf: "Imprimer / Enregistrer PDF",
        copySummary: "Copier le résumé",
        current: "Entrée actuelle",
        check: "Vérification",
        output: "Sortie du scénario",
        roleQuestion: "Q1. Sous quel angle professionnel souhaitez-vous construire ce scénario ?",
        countryQuestion: "Q2. Pour quel pays ce scénario est-il destiné ?",
        personaQuestion: "Q3. Quel utilisateur et quelle situation avez-vous en tête ?",
        deviceQuestion: "Q4. Quel appareil doit être au centre du scénario ?",
        purposePlaceholder: "Exemple : une famille avec deux revenus souhaite commencer la soirée plus vite et plus confortablement après son retour à la maison avec son enfant.",
        countryHelper: "Les appareils recommandés et les angles narratifs peuvent varier selon le marché.",
        personaHelper: "Ajoutez l'âge, le mode de vie, la saison et les problèmes à la maison pour rendre le scénario plus convaincant.",
        deviceHelper: "Choisir une catégorie d'appareil rend le scénario plus flexible et évolutif.",
        roleMissing: "Veuillez d'abord choisir l'angle professionnel dans la Q1.",
        countryMissing: "Veuillez choisir le pays dans la Q2.",
        personaMissing: "Dans la Q3, sélectionnez le type d'utilisateur ou décrivez la situation.",
        allMissing: "Veuillez compléter les quatre questions avant de générer le scénario.",
        downloadFirst: "Veuillez d'abord générer un scénario.",
        summaryState: "Résumé des entrées",
        detailedScenario: "Scénario détaillé",
        automation: "Flux d'automatisation",
        facts: "Base du scénario",
        confirmed: "Informations confirmées",
        assumptions: "Notes",
        lenses: "Usages par rôle",
        effects: "Impact attendu",
        segment: "Public recommandé",
        guide: "Premiers pas",
        evaluation: "Évaluation",
        why: "Pourquoi",
        comparison: "Comparaison",
        note: "Note",
        roleLens: "Vue par rôle",
        executionPoints: "Points d'exécution",
        summary: "Résumé",
        fit: "Bon",
        review: "À revoir",
        fitCheck: "Pertinence du scénario",
        availabilityCheck: "Disponibilité de l'appareil",
        executionCheck: "Faisabilité",
        clarityCheck: "Clarté du message",
        metricCheck: "Lien avec le résultat"
    },
    es: {
        enterAgent: "Entrar al agente",
        accessRequired: "Por favor, introduce el código de acceso.",
        accessPlaceholder: "Introducir código de acceso",
        accessHelper: "El código de acceso se verifica en el servidor y te lleva al siguiente paso en cuanto se aprueba.",
        guideTitle: "¿Sabes cómo usar este agente?",
        guideQuick: "Guía Rápida",
        guideLine1: "Las preguntas aparecen una por una.",
        guideLine2: "Después de cada respuesta, recibirás una pista breve para orientar el siguiente paso.",
        guideLine3: "Cuando completes los cuatro pasos, se generará de inmediato un escenario utilizable.",
        startAfterGuide: "Bien. Empezaremos desde la Q1 paso a paso, con una pista breve después de cada respuesta.",
        unlockedPlaceholder: "Después de esta breve verificación, comenzarás desde la Q1.",
        stateMissing: "Tus selecciones actuales aparecerán aquí a medida que respondas.",
        checkPlaceholder: "Aquí aparecerá una revisión rápida de la estructura después de generar el escenario.",
        outputPlaceholder: "Después del acceso y de responder las cuatro preguntas, verás el escenario detallado y las aplicaciones por rol.",
        progress1: "Q1 Enfoque",
        progress2: "Q2 Región",
        progress3: "Q3 Usuario y contexto",
        progress4: "Q4 Dispositivo",
        prev: "Atrás",
        next: "Siguiente",
        build: "Crear escenario",
        downloadMarkdown: "Descargar Markdown",
        downloadJson: "Descargar JSON",
        printPdf: "Imprimir / Guardar PDF",
        copySummary: "Copiar resumen",
        current: "Entrada actual",
        check: "Revisión",
        output: "Resultado del escenario",
        roleQuestion: "Q1. ¿Desde qué perspectiva profesional quieres crear este escenario?",
        countryQuestion: "Q2. ¿Para qué país es este escenario?",
        personaQuestion: "Q3. ¿Qué usuario y qué situación tienes en mente?",
        deviceQuestion: "Q4. ¿Qué dispositivo debe ser el eje del escenario?",
        purposePlaceholder: "Ejemplo: una familia con doble ingreso quiere empezar la noche de forma más rápida y cómoda al llegar a casa con su hijo.",
        countryHelper: "Los dispositivos recomendados y los enfoques narrativos pueden variar según el mercado.",
        personaHelper: "Añade edad, estilo de vida, temporada y problemas del hogar para que el escenario sea más convincente.",
        deviceHelper: "Elegir una categoría de dispositivo hace que el escenario sea más flexible y ampliable.",
        roleMissing: "Primero elige la perspectiva profesional en la Q1.",
        countryMissing: "Elige el país en la Q2.",
        personaMissing: "En la Q3, selecciona el tipo de usuario o describe la situación.",
        allMissing: "Completa las cuatro preguntas antes de generar el escenario.",
        downloadFirst: "Primero genera un escenario.",
        summaryState: "Resumen de entrada",
        detailedScenario: "Escenario detallado",
        automation: "Flujo de automatización",
        facts: "Base del escenario",
        confirmed: "Información confirmada",
        assumptions: "Notas",
        lenses: "Usos por rol",
        effects: "Impacto esperado",
        segment: "Audiencia recomendada",
        guide: "Primeros pasos",
        evaluation: "Evaluación",
        why: "Por qué",
        comparison: "Comparación",
        note: "Nota",
        roleLens: "Vista por rol",
        executionPoints: "Puntos de ejecución",
        summary: "Resumen",
        fit: "Adecuado",
        review: "Revisar",
        fitCheck: "Ajuste del escenario",
        availabilityCheck: "Disponibilidad del dispositivo",
        executionCheck: "Viabilidad",
        clarityCheck: "Claridad del mensaje",
        metricCheck: "Vínculo con el resultado"
    },
    pt: {
        enterAgent: "Entrar no agente",
        accessRequired: "Insira o código de acesso.",
        accessPlaceholder: "Inserir código de acesso",
        accessHelper: "O código de acesso é verificado no servidor e, quando aprovado, você segue direto para a próxima etapa.",
        guideTitle: "Você sabe como usar este agente?",
        guideQuick: "Guia Rápido",
        guideLine1: "As perguntas aparecem uma de cada vez.",
        guideLine2: "Após cada resposta, você recebe uma dica curta para orientar o próximo passo.",
        guideLine3: "Depois de concluir as quatro etapas, um cenário utilizável é gerado imediatamente.",
        startAfterGuide: "Ótimo. Vamos começar pela Q1 passo a passo, com uma dica curta após cada resposta.",
        unlockedPlaceholder: "Após esta verificação rápida, você começará pela Q1.",
        stateMissing: "Suas seleções atuais aparecerão aqui conforme você responder.",
        checkPlaceholder: "Uma verificação rápida da estrutura aparecerá aqui após a geração do cenário.",
        outputPlaceholder: "Após o acesso e as quatro perguntas, você verá o cenário detalhado e as aplicações por função.",
        progress1: "Q1 Função",
        progress2: "Q2 Região",
        progress3: "Q3 Usuário e contexto",
        progress4: "Q4 Dispositivo",
        prev: "Voltar",
        next: "Próximo",
        build: "Criar cenário",
        downloadMarkdown: "Baixar Markdown",
        downloadJson: "Baixar JSON",
        printPdf: "Imprimir / Salvar PDF",
        copySummary: "Copiar resumo",
        current: "Entrada atual",
        check: "Verificação",
        output: "Saída do cenário",
        roleQuestion: "Q1. De qual perspectiva profissional você quer construir este cenário?",
        countryQuestion: "Q2. Para qual país este cenário é destinado?",
        personaQuestion: "Q3. Que usuário e situação você tem em mente?",
        deviceQuestion: "Q4. Qual dispositivo deve estar no centro do cenário?",
        purposePlaceholder: "Exemplo: uma família com dupla renda quer começar a noite de forma mais rápida e confortável ao chegar em casa com o filho.",
        countryHelper: "Os dispositivos recomendados e os ângulos de narrativa podem variar conforme o mercado.",
        personaHelper: "Adicione idade, estilo de vida, estação e problemas em casa para deixar o cenário mais convincente.",
        deviceHelper: "Escolher uma categoria de dispositivo mantém o cenário mais flexível e expansível.",
        roleMissing: "Primeiro escolha a perspectiva profissional na Q1.",
        countryMissing: "Escolha o país na Q2.",
        personaMissing: "Na Q3, selecione o tipo de usuário ou descreva a situação.",
        allMissing: "Conclua as quatro perguntas antes de gerar o cenário.",
        downloadFirst: "Gere um cenário primeiro.",
        summaryState: "Resumo da entrada",
        detailedScenario: "Cenário detalhado",
        automation: "Fluxo de automação",
        facts: "Base do cenário",
        confirmed: "Informações confirmadas",
        assumptions: "Notas",
        lenses: "Usos por função",
        effects: "Impacto esperado",
        segment: "Público recomendado",
        guide: "Primeiros passos",
        evaluation: "Avaliação",
        why: "Por quê",
        comparison: "Comparação",
        note: "Nota",
        roleLens: "Visão por função",
        executionPoints: "Pontos de execução",
        summary: "Resumo",
        fit: "Adequado",
        review: "Revisar",
        fitCheck: "Adequação do cenário",
        availabilityCheck: "Disponibilidade do dispositivo",
        executionCheck: "Viabilidade",
        clarityCheck: "Clareza da mensagem",
        metricCheck: "Ligação com o resultado"
    },
    it: {
        enterAgent: "Entra nell'agente",
        accessRequired: "Inserisci il codice di accesso.",
        accessPlaceholder: "Inserisci codice di accesso",
        accessHelper: "Il codice di accesso viene verificato sul server e, quando approvato, passa subito allo step successivo.",
        guideTitle: "Sai come usare questo agente?",
        guideQuick: "Guida Rapida",
        guideLine1: "Le domande appaiono una alla volta.",
        guideLine2: "Dopo ogni risposta ricevi un breve suggerimento per orientare il passo successivo.",
        guideLine3: "Dopo quattro passaggi viene generato subito uno scenario utilizzabile.",
        startAfterGuide: "Bene. Inizieremo dalla Q1 passo dopo passo, con un breve suggerimento dopo ogni risposta.",
        unlockedPlaceholder: "Dopo questa breve verifica inizierai dalla Q1.",
        stateMissing: "Le tue selezioni attuali appariranno qui mentre rispondi.",
        checkPlaceholder: "Qui comparirà un rapido controllo della struttura dopo la generazione dello scenario.",
        outputPlaceholder: "Dopo l'accesso e le quattro domande vedrai lo scenario dettagliato e le applicazioni per ruolo.",
        progress1: "Q1 Ruolo",
        progress2: "Q2 Regione",
        progress3: "Q3 Utente e contesto",
        progress4: "Q4 Dispositivo",
        prev: "Indietro",
        next: "Avanti",
        build: "Crea scenario",
        downloadMarkdown: "Scarica Markdown",
        downloadJson: "Scarica JSON",
        printPdf: "Stampa / Salva PDF",
        copySummary: "Copia riepilogo",
        current: "Input attuale",
        check: "Controllo",
        output: "Output scenario",
        roleQuestion: "Q1. Da quale prospettiva professionale vuoi costruire questo scenario?",
        countryQuestion: "Q2. Per quale paese è pensato questo scenario?",
        personaQuestion: "Q3. Quale utente e quale situazione hai in mente?",
        deviceQuestion: "Q4. Quale dispositivo deve stare al centro dello scenario?",
        purposePlaceholder: "Esempio: una famiglia con doppio reddito vuole iniziare la serata in modo più rapido e confortevole appena rientra a casa con il figlio.",
        countryHelper: "I dispositivi consigliati e gli angoli narrativi possono cambiare in base al mercato.",
        personaHelper: "Aggiungi età, stile di vita, stagione e problemi in casa per rendere lo scenario più convincente.",
        deviceHelper: "Scegliere una categoria di dispositivo rende lo scenario più flessibile ed estendibile.",
        roleMissing: "Per prima cosa scegli la prospettiva professionale nella Q1.",
        countryMissing: "Scegli il paese nella Q2.",
        personaMissing: "Nella Q3, seleziona il tipo di utente o descrivi la situazione.",
        allMissing: "Completa tutte e quattro le domande prima di generare lo scenario.",
        downloadFirst: "Genera prima uno scenario.",
        summaryState: "Riepilogo input",
        detailedScenario: "Scenario dettagliato",
        automation: "Flusso di automazione",
        facts: "Base dello scenario",
        confirmed: "Informazioni confermate",
        assumptions: "Note",
        lenses: "Usi per ruolo",
        effects: "Impatto atteso",
        segment: "Pubblico consigliato",
        guide: "Primi passi",
        evaluation: "Valutazione",
        why: "Perché",
        comparison: "Confronto",
        note: "Nota",
        roleLens: "Vista per ruolo",
        executionPoints: "Punti di esecuzione",
        summary: "Riepilogo",
        fit: "Adatto",
        review: "Da rivedere",
        fitCheck: "Aderenza dello scenario",
        availabilityCheck: "Disponibilità del dispositivo",
        executionCheck: "Fattibilità",
        clarityCheck: "Chiarezza del messaggio",
        metricCheck: "Collegamento al risultato"
    },
    nl: {
        enterAgent: "Agent openen",
        accessRequired: "Voer de toegangscode in.",
        accessPlaceholder: "Toegangscode invoeren",
        accessHelper: "De toegangscode wordt op de server gecontroleerd en gaat na goedkeuring direct door naar de volgende stap.",
        guideTitle: "Weet je hoe je deze agent gebruikt?",
        guideQuick: "Snelle gids",
        guideLine1: "De vragen verschijnen één voor één.",
        guideLine2: "Na elk antwoord krijg je een korte hint voor de volgende richting.",
        guideLine3: "Na vier stappen wordt direct een bruikbaar scenario gegenereerd.",
        startAfterGuide: "Goed. We beginnen nu stap voor stap bij Q1, met na elk antwoord een korte hint voor de volgende richting.",
        unlockedPlaceholder: "Na deze korte controle begin je bij Q1.",
        stateMissing: "Je huidige keuzes verschijnen hier terwijl je antwoordt.",
        checkPlaceholder: "Na het genereren verschijnt hier een snelle structuurcontrole.",
        outputPlaceholder: "Na toegang en vier vragen zie je het gedetailleerde scenario en de toepassingen per rol.",
        progress1: "Q1 Rol",
        progress2: "Q2 Regio",
        progress3: "Q3 Gebruiker en context",
        progress4: "Q4 Apparaat",
        prev: "Terug",
        next: "Volgende",
        build: "Scenario maken",
        downloadMarkdown: "Markdown downloaden",
        downloadJson: "JSON downloaden",
        printPdf: "Afdrukken / PDF opslaan",
        copySummary: "Samenvatting kopiëren",
        current: "Huidige invoer",
        check: "Controle",
        output: "Scenario-uitvoer",
        roleQuestion: "Q1. Vanuit welk professioneel perspectief wil je dit scenario opbouwen?",
        countryQuestion: "Q2. Voor welk land is dit scenario bedoeld?",
        personaQuestion: "Q3. Welke gebruiker en situatie heb je in gedachten?",
        deviceQuestion: "Q4. Welk apparaat moet centraal staan?",
        purposePlaceholder: "Voorbeeld: een gezin met twee inkomens wil de avond sneller en comfortabeler starten zodra het met het kind thuiskomt.",
        countryHelper: "Aanbevolen apparaten en verhaalhoeken kunnen per markt verschillen.",
        personaHelper: "Voeg leeftijd, levensstijl, seizoen en problemen thuis toe om het scenario overtuigender te maken.",
        deviceHelper: "Een apparaatcategorie kiezen houdt het scenario flexibeler en beter uitbreidbaar.",
        roleMissing: "Kies eerst het professionele perspectief in Q1.",
        countryMissing: "Kies het land in Q2.",
        personaMissing: "Kies in Q3 het gebruikerstype of beschrijf de situatie.",
        allMissing: "Voltooi eerst alle vier de vragen.",
        downloadFirst: "Genereer eerst een scenario.",
        summaryState: "Invoeroverzicht",
        detailedScenario: "Gedetailleerd scenario",
        automation: "Automatiseringsstroom",
        facts: "Basis van het scenario",
        confirmed: "Bevestigde informatie",
        assumptions: "Notities",
        lenses: "Gebruik per rol",
        effects: "Verwachte impact",
        segment: "Aanbevolen doelgroep",
        guide: "Aan de slag",
        evaluation: "Beoordeling",
        why: "Waarom",
        comparison: "Vergelijking",
        note: "Opmerking",
        roleLens: "Rolweergave",
        executionPoints: "Uitvoeringspunten",
        summary: "Samenvatting",
        fit: "Passend",
        review: "Herzien",
        fitCheck: "Scenario-fit",
        availabilityCheck: "Beschikbaarheid apparaat",
        executionCheck: "Uitvoerbaarheid",
        clarityCheck: "Duidelijkheid boodschap",
        metricCheck: "Koppeling aan resultaat"
    },
    ar: {
        enterAgent: "دخول الوكيل",
        accessRequired: "يرجى إدخال رمز الوصول.",
        accessPlaceholder: "أدخل رمز الوصول",
        accessHelper: "يتم التحقق من رمز الوصول على الخادم، وعند اعتماده تنتقل مباشرة إلى الخطوة التالية.",
        guideTitle: "هل تعرف كيفية استخدام هذا الوكيل؟",
        guideQuick: "دليل سريع",
        guideLine1: "تظهر الأسئلة واحداً تلو الآخر.",
        guideLine2: "بعد كل إجابة تحصل على تلميح قصير يوجّه الخطوة التالية.",
        guideLine3: "بعد إكمال الخطوات الأربع يتم إنشاء سيناريو قابل للاستخدام فوراً.",
        startAfterGuide: "جيد. سنبدأ من Q1 خطوة بخطوة، مع تلميح قصير بعد كل إجابة لتوضيح الاتجاه التالي.",
        unlockedPlaceholder: "بعد هذا التحقق السريع ستبدأ من Q1.",
        stateMissing: "ستظهر اختياراتك الحالية هنا أثناء الإجابة.",
        checkPlaceholder: "سيظهر هنا فحص سريع للبنية بعد إنشاء السيناريو.",
        outputPlaceholder: "بعد الوصول والإجابة عن الأسئلة الأربعة سترى السيناريو المفصل والتطبيقات حسب الدور.",
        progress1: "Q1 الدور",
        progress2: "Q2 المنطقة",
        progress3: "Q3 المستخدم والسياق",
        progress4: "Q4 الجهاز",
        prev: "السابق",
        next: "التالي",
        build: "إنشاء السيناريو",
        downloadMarkdown: "تنزيل Markdown",
        downloadJson: "تنزيل JSON",
        printPdf: "طباعة / حفظ PDF",
        copySummary: "نسخ الملخص",
        current: "المدخل الحالي",
        check: "فحص البنية",
        output: "مخرجات السيناريو",
        roleQuestion: "Q1. من أي منظور مهني تريد بناء هذا السيناريو؟",
        countryQuestion: "Q2. لأي دولة هذا السيناريو؟",
        personaQuestion: "Q3. ما المستخدم والموقف اللذان تفكر فيهما؟",
        deviceQuestion: "Q4. ما الجهاز الذي يجب أن يكون محور السيناريو؟",
        purposePlaceholder: "مثال: ترغب أسرة ذات دخلين في بدء المساء بشكل أسرع وأكثر راحة بعد العودة إلى المنزل مع الطفل.",
        countryHelper: "قد تختلف الأجهزة المقترحة وزوايا السرد حسب السوق.",
        personaHelper: "أضف العمر ونمط الحياة والموسم والمشكلات المنزلية لجعل السيناريو أكثر إقناعاً.",
        deviceHelper: "اختيار فئة جهاز يجعل السيناريو أكثر مرونة وقابلية للتوسع.",
        roleMissing: "يرجى اختيار المنظور المهني أولاً في Q1.",
        countryMissing: "يرجى اختيار الدولة في Q2.",
        personaMissing: "في Q3، يرجى اختيار نوع المستخدم أو وصف الموقف.",
        allMissing: "يرجى إكمال الأسئلة الأربعة قبل إنشاء السيناريو.",
        downloadFirst: "يرجى إنشاء سيناريو أولاً.",
        summaryState: "ملخص الإدخال",
        detailedScenario: "السيناريو التفصيلي",
        automation: "تدفق الأتمتة",
        facts: "أساس السيناريو",
        confirmed: "معلومات مؤكدة",
        assumptions: "ملاحظات",
        lenses: "الاستخدام حسب الدور",
        effects: "الأثر المتوقع",
        segment: "الجمهور المقترح",
        guide: "البدء",
        evaluation: "التقييم",
        why: "لماذا",
        comparison: "المقارنة",
        note: "ملاحظة",
        roleLens: "منظور الدور",
        executionPoints: "نقاط التنفيذ",
        summary: "الملخص",
        fit: "مناسب",
        review: "يحتاج مراجعة",
        fitCheck: "ملاءمة السيناريو",
        availabilityCheck: "توفر الجهاز",
        executionCheck: "قابلية التنفيذ",
        clarityCheck: "وضوح الرسالة",
        metricCheck: "الارتباط بالنتيجة"
    }
};
