const UI_TEXT = {
    ko: {
        enterAgent: "Enter Agent",
        heroEyebrow: "Interactive Scenario Builder",
        heroText: "핵심 입력만 선택하면 메시지부터 활용안까지 완성도 높은 시나리오로 정리됩니다.",
        heroChip1: "맥락 중심 설계",
        heroChip2: "4단계 guided flow",
        heroChip3: "바로 검토 가능한 결과",
        heroFlow1: "접근 확인 후 시작 가이드",
        heroFlow2: "질문에 따라 단계별 입력",
        heroFlow3: "결과 확인과 바로 내보내기",
        getStarted: "시작하기",
        guideYes: "Yes",
        guideNo: "No",
        guideStart: "시작",
        q3Guide: "A·B·C 각 영역에서 최소 1개를 선택하거나 직접 입력해 주세요. 조합이 구체적일수록 시나리오가 날카로워집니다.",
        cityCustomPlaceholder: "도시 / 주 / 지역 직접 입력",
        deviceCustomPlaceholder: "추가 기기나 세부 모델을 직접 입력",
        purposeExtraPlaceholder: "위 선택 외에 추가로 떠오르는 상황이 있다면 자유롭게 적어 주세요",
        accessRequired: "접근 코드를 입력해 주세요.",
        accessPlaceholder: "접근 코드 입력",
        accessHelper: "접근 코드는 서버에서 확인되며, 승인되면 바로 다음 단계로 이어집니다.",
        accessVerifying: "접근 코드를 확인하고 있습니다.",
        accessInvalid: "유효하지 않은 접근 코드입니다.",
        accessInvalidRemaining: "유효하지 않은 접근 코드입니다. 남은 시도 {count}회.",
        accessLocked: "실패 횟수가 많아 잠시 잠겼습니다. 잠시 후 다시 시도해 주세요.",
        accessLockedWithTime: "실패 횟수가 많아 잠시 잠겼습니다. {time} 후에 다시 시도해 주세요.",
        accessLockedNewWindow: "3회 연속 실패로 이 창은 잠겼습니다. {time} 후 다시 시도하거나 새 창에서 다시 시작해 주세요.",
        accessUnavailable: "접근 코드 검증 서버에 연결할 수 없습니다.",
        accessGranted: "접근이 확인되었습니다. 가이드를 여는 중입니다.",
        accessShow: "보기",
        accessHide: "숨기기",
        logout: "로그아웃",
        loggedOut: "세션이 종료되었습니다. 다시 접근 코드를 입력해 주세요.",
        guideTitle: "사용 방법을 아시나요?",
        guideQuick: "Quick Guide",
        guideLine1: "질문은 한 번에 하나씩 열립니다.",
        guideLine2: "답변을 마칠 때마다 다음 방향을 넓혀주는 힌트가 제공됩니다.",
        guideLine3: "네 단계를 마치면 바로 활용 가능한 시나리오가 정리됩니다.",
        startAfterGuide: "좋아요. 이제 Q1부터 한 단계씩 진행할게요. 각 답변 뒤에 다음 방향을 더 선명하게 만드는 힌트를 함께 보여드립니다.",
        unlockedPlaceholder: "사용 방법 확인 후 Q1부터 차례대로 시작합니다.",
        stateMissing: "질문에 답하면 현재 선택한 내용이 여기에 정리됩니다.",
        checkPlaceholder: "시나리오를 생성하면 구성 점검 결과가 표시됩니다.",
        outputPlaceholder: "접근 확인 후 네 가지 질문을 순서대로 완료하면 상세 시나리오와 역할별 활용안을 확인할 수 있습니다.",
        progress1: "Q1 담당 업무",
        progress2: "Q2 지역",
        progress3: "Q3 타겟 고객 및 상황",
        progress4: "Q4 반영 기기",
        prev: "이전",
        next: "다음",
        build: "Scenario Build",
        downloadMarkdown: "Download Markdown",
        downloadJson: "Download JSON",
        printPdf: "Print / Save PDF",
        copySummary: "Copy Summary",
        current: "입력 요약",
        check: "구성 점검",
        output: "Scenario Output",
        roleQuestion: "Q1. 어떤 관점에서 시나리오를 만들고 싶나요?",
        countryQuestion: "Q2. 어느 국가를 대상으로 하나요?",
        personaQuestion: "Q3. 타겟의 생활 맥락을 잡아 주세요",
        deviceQuestion: "Q4. 어떤 기기를 중심으로 구성할까요?",
        purposePlaceholder: "예: 맞벌이 가정이 퇴근 후 아이와 함께 집에 들어왔을 때 더 빠르고 편안하게 저녁 시간을 시작하고 싶다",
        countryHelper: "국가와 지역을 고르면 어떤 생활 장면이 더 설득력 있게 읽히는지 바로 좁혀집니다.",
        personaHelper: "가구 유형과 생활 맥락을 함께 고르면 타겟이 더 선명해지고, 시나리오 톤도 달라집니다.",
        deviceHelper: "상위 카테고리를 먼저 고르고 필요한 기기만 남기면 실제 사용 장면이 훨씬 빠르게 잡힙니다.",
        roleMissing: "Q1에서 담당 업무 관점을 먼저 선택해 주세요.",
        countryMissing: "Q2에서 국가를 선택해 주세요.",
        personaMissing: "Q3에서 타겟 세그먼트를 선택하거나 상황 설명을 입력해 주세요.",
        allMissing: "네 가지 질문을 모두 완료한 뒤 다시 시도해 주세요.",
        downloadFirst: "먼저 시나리오를 생성해 주세요.",
        summaryState: "Input Summary",
        detailedScenario: "상세 시나리오",
        automation: "자동화 흐름",
        facts: "구성 근거",
        confirmed: "확정 정보",
        assumptions: "참고 메모",
        lenses: "활용 관점",
        effects: "기대 효과",
        segment: "추천 사용자",
        guide: "시작 가이드",
        evaluation: "활용 판단",
        why: "Why",
        comparison: "Comparison",
        note: "Note",
        roleLens: "Role Lens",
        executionPoints: "실행 포인트",
        summary: "요약",
        fit: "적합",
        review: "재검토 필요",
        fitCheck: "구성 적합성",
        availabilityCheck: "기기 가용성",
        executionCheck: "실행 가능성",
        clarityCheck: "메시지 명확성",
        metricCheck: "성과 연결성",
        previewTitle: "Q1~Q4를 완료하면 아래 구성으로 결과가 생성됩니다.",
        prev01Title: "시나리오 요약", prev01Desc: "타겟 고객과 핵심 가치가 한눈에 정리됩니다.",
        prev02Title: "상세 시나리오", prev02Desc: "타겟 고객과 적용 서비스, Pain-해결-Benefit 구조의 시나리오 카드가 정리됩니다.",
        prev03Title: "지역 맞춤 인사이트", prev03Desc: "Observation-Insight-Implication 구조로 왜 이 시장에서 먹히는지 설명합니다.",
        prev04Title: "마케팅 메시지", prev04Desc: "직무에 맞는 메시지와 카피 옵션을 비교해 볼 수 있습니다.",
        prev05Title: "주요 고객 혜택", prev05Desc: "사용자가 직접 느끼는 이점을 우선순위로 정리합니다.",
        prev06Title: "타겟 및 수용도 분석", prev06Desc: "좋아할 점과 우려할 점을 함께 보고 수용도를 판단합니다.",
        prev07Title: "캠페인 타이밍 및 방향", prev07Desc: "언제, 어떤 장면으로 밀어야 하는지 바로 연결합니다.",
        exportPdf: "PDF 저장", exportPdfDesc: "회의 공유 / 이메일 첨부용",
        exportWord: "Word 저장", exportWordDesc: "편집 및 협업용",
        exportExcel: "Excel 저장", exportExcelDesc: "데이터 테이블 정리용",
        exportCopy: "클립보드 복사", exportCopyDesc: "메신저 / 메일 본문용",
        outputLabel: "Output", outputTitle: "시나리오 출력",
        outTitle01: "01. 시나리오 제목 및 요약",
        outTitle02: "02. 상세 시나리오",
        outTitle03: "03. 지역 맞춤 인사이트",
        outTitle04: "04. 마케팅 메시지",
        outTitle05: "05. 고객 베네핏",
        outTitle06: "06. 타겟 세그먼트 및 고객 수용도 분석",
        outTitle07: "07. 캠페인 타이밍 및 크리에이티브 방향",
        outTitle08: "08. 기기 구성 및 설정 가이드",
        outTitle09: "09. 시나리오 시장성 평가 (리스크 포함)",
        outTitle10: "10. 실행 확장 팩 — 고객 적용 가이드 + 성과 지표 연결",
        outTitle11: "11. 브랜드/AI/철학 품질 점검",
        guideHeroTitle: "4단계 입력만으로<br>완성도 높은 시나리오를<br>만듭니다",
        guideLead: "핵심만 빠르게 선택하고, 필요한 정보만 더해 바로 검토할 수 있는 결과로 정리합니다.",
        guideInputsTitle: "먼저 기준이 되는 4가지를 정합니다",
        guideQ1: "Q1 담당업무", guideQ1Desc: "리테일, 닷컴 캠페인, 브랜드 마케팅 중 관점을 고릅니다.",
        guideQ2: "Q2 국가·지역", guideQ2Desc: "대상 국가와 도시 또는 주를 함께 정합니다.",
        guideQ3: "Q3 타겟 고객", guideQ3Desc: "가구 특성, 시즌, 생활 맥락을 짧게 적습니다.",
        guideQ4: "Q4 기기·환경", guideQ4Desc: "핵심 기기 조합과 실제 제약 조건을 선택합니다.",
        guideFlowTitle: "입력은 간결하게, 결과는 더 선명하게",
        guideFlowStep: "질문은 한 번에 하나씩 열려 흐름이 명확합니다.",
        guideFlowLean: "필요할 때만 추가 확인 포인트를 최소로 더합니다.",
        guideFlowClear: "불확실한 내용은 가정 사항으로 분리해 결과의 완성도를 유지합니다.",
        guideNote: "가이드를 확인했다면 아래 시작 버튼으로 바로 첫 번째 질문부터 시작하세요. 짧은 입력만으로도 검토와 공유에 바로 쓸 수 있는 결과를 만듭니다.",
        personaTask: "주요 과제", personaSuccess: "기대 결과",
        stateRole: "담당업무", stateCountry: "국가", statePersona: "타겟고객",
        stateSituation: "상황설명", stateDevice: "반영기기",
        notSelected: "미선택", notEntered: "미입력",
        guideSessionNote: "Logout은 현재 인증 세션을 종료하고, 접근 코드 입력 화면으로 돌아갑니다.",
        nudgeNow: "지금 상황", nudgeNeed: "예상 니즈", nudgeOpportunity: "기회 포인트",
        q3AutoBtn: "지역 트렌드 기반 자동 구성 — AI가 국가·도시에 맞는 타겟 세그먼트를 선택합니다",
        q4AutoBtn: "트렌드 기반 자동 구성 — AI가 지역·세그먼트에 맞는 최적 기기를 선택합니다",
        q4PresetTitle: "반영 기기 스타일별 조합",
        q4DirectTitle: "기기 직접 선택",
        q4DetailSummary: "카테고리별 상세 기기 보기",
        q4SummaryTitle: "현재 조합 요약"
    },
    en: {
        enterAgent: "Enter Agent",
        heroEyebrow: "Interactive Scenario Builder",
        heroText: "Answer the questions in sequence and build an app scenario step by step that feels more compelling to users.",
        heroChip1: "Context-first flow",
        heroChip2: "4 guided inputs",
        heroChip3: "Review-ready output",
        heroFlow1: "Access and guide check",
        heroFlow2: "Step-by-step scenario setup",
        heroFlow3: "Immediate output and export",
        getStarted: "Get Started",
        guideYes: "Yes",
        guideNo: "No",
        guideStart: "Start",
        q3Guide: "Pick at least one from each of A, B, and C (or type your own). The more specific the combo, the sharper the scenario.",
        cityCustomPlaceholder: "Type city / state / region",
        deviceCustomPlaceholder: "Add any extra device or model",
        purposeExtraPlaceholder: "Any extra context beyond the selections above",
        accessRequired: "Please enter the access code.",
        accessPlaceholder: "Enter access code",
        accessHelper: "The access code is verified on the server and creates a session on success.",
        accessVerifying: "Verifying your access code.",
        accessInvalid: "Invalid access code.",
        accessInvalidRemaining: "Invalid access code. {count} attempts remaining.",
        accessLocked: "Too many failed attempts. Try again later.",
        accessLockedWithTime: "Too many failed attempts. Try again in {time}.",
        accessLockedNewWindow: "This tab is locked after 3 failed attempts. Try again in {time}, or start again in a new tab.",
        accessUnavailable: "The access verification server is unavailable.",
        accessGranted: "Access confirmed. Opening the guide.",
        accessShow: "Show",
        accessHide: "Hide",
        logout: "Logout",
        loggedOut: "Your session has been signed out. Enter the access code again.",
        guideTitle: "Do you know how to use this agent?",
        guideQuick: "Quick Guide",
        guideLine1: "Questions appear one at a time.",
        guideLine2: "After each answer, you get a short prompt that expands the next direction.",
        guideLine3: "Once all four steps are complete, a practical scenario is generated immediately.",
        startAfterGuide: "Good. We will start from Q1 step by step, with a short prompt after each answer to sharpen the next direction.",
        unlockedPlaceholder: "After the usage check, you will start from Q1 in sequence.",
        stateMissing: "Your current selections will appear here as you answer each question.",
        checkPlaceholder: "A quick structure check will appear after the scenario is generated.",
        outputPlaceholder: "After access confirmation and all four questions, you will see the detailed scenario and role-based applications.",
        progress1: "Q1 Work Lens",
        progress2: "Q2 Region",
        progress3: "Q3 User & Context",
        progress4: "Q4 Device",
        prev: "Back",
        next: "Next",
        build: "Scenario Build",
        downloadMarkdown: "Download Markdown",
        downloadJson: "Download JSON",
        printPdf: "Print / Save PDF",
        copySummary: "Copy Summary",
        current: "Current Input",
        check: "Structure Check",
        output: "Scenario Output",
        roleQuestion: "Q1. From which professional lens do you want to build this scenario?",
        countryQuestion: "Q2. Which country is this for?",
        personaQuestion: "Q3. Define the target's living context",
        deviceQuestion: "Q4. Which device should anchor the scenario?",
        purposePlaceholder: "Example: A dual-income family wants to start the evening faster and more comfortably right after arriving home with their child.",
        countryHelper: "Pick the market and region first to narrow which life moment will feel most convincing.",
        personaHelper: "Combine household type and living context to make the target sharper and the scenario tone more specific.",
        deviceHelper: "Start with a top category, then trim the device list to the exact mix you want to frame.",
        roleMissing: "Please choose the work lens first in Q1.",
        countryMissing: "Please choose the country in Q2.",
        personaMissing: "In Q3, choose the target segment or describe the situation.",
        allMissing: "Please complete all four questions before generating the scenario.",
        downloadFirst: "Please generate a scenario first.",
        summaryState: "Input Summary",
        detailedScenario: "Detailed Scenario",
        automation: "Automation Flow",
        facts: "Scenario Basis",
        confirmed: "Confirmed Info",
        assumptions: "Notes",
        lenses: "Use Cases by Role",
        effects: "Expected Impact",
        segment: "Recommended Audience",
        guide: "Getting Started",
        evaluation: "Evaluation",
        why: "Why",
        comparison: "Comparison",
        note: "Note",
        roleLens: "Role Lens",
        executionPoints: "Execution Points",
        summary: "Summary",
        fit: "Good",
        review: "Needs Review",
        fitCheck: "Scenario Fit",
        availabilityCheck: "Device Availability",
        executionCheck: "Execution Feasibility",
        clarityCheck: "Message Clarity",
        metricCheck: "Outcome Linkage",
        previewTitle: "Complete Q1–Q4 and receive your results in this structure.",
        prev01Title: "Scenario Summary", prev01Desc: "Target customer and core value proposition at a glance.",
        prev02Title: "Detailed Scenario", prev02Desc: "Target customer, applied services, and scenario cards with pain, resolution, and benefit.",
        prev03Title: "Local Insight", prev03Desc: "Explain why this works in the market through Observation, Insight, and Implication.",
        prev04Title: "Marketing Messages", prev04Desc: "Compare campaign-ready copy options tuned to the selected role.",
        prev05Title: "Customer Benefits", prev05Desc: "Prioritize the user benefits that will persuade most clearly.",
        prev06Title: "Target & Acceptance Read", prev06Desc: "Estimate likely likes, concerns, and acceptance before execution.",
        prev07Title: "Timing & Creative Direction", prev07Desc: "Connect the scenario to campaign timing and usable story direction.",
        exportPdf: "Save PDF", exportPdfDesc: "For meetings & email attachments",
        exportWord: "Save Word", exportWordDesc: "Editable document for collaboration",
        exportExcel: "Save Excel", exportExcelDesc: "Structured data tables",
        exportCopy: "Copy to Clipboard", exportCopyDesc: "Quick paste & share",
        outputLabel: "Output", outputTitle: "Scenario Output",
        outTitle01: "01. Title & Summary",
        outTitle02: "02. Detailed Scenario",
        outTitle03: "03. Local Insight",
        outTitle04: "04. Marketing Messages",
        outTitle05: "05. Customer Benefits",
        outTitle06: "06. Target Segment & Acceptance Read",
        outTitle07: "07. Timing & Creative Direction",
        outTitle08: "08. Available Devices & Setup Guide",
        outTitle09: "09. Marketability & Risk Evaluation",
        outTitle10: "10. Add-on Pack — Implementation & Funnel Mapping",
        outTitle11: "11. Brand/AI/Philosophy Reflection",
        guideHeroTitle: "Build a usable scenario<br>from four guided inputs",
        guideLead: "Pick the essentials first. The agent turns them into a sharper, review-ready scenario.",
        guideInputsTitle: "What you set first",
        guideQ1: "Q1 Work Lens", guideQ1Desc: "Retail, Dotcom Campaign, or Brand Marketing",
        guideQ2: "Q2 Country & Region", guideQ2Desc: "Target market plus city, state, or region",
        guideQ3: "Q3 Target Customer", guideQ3Desc: "Household type, season, and real-life context",
        guideQ4: "Q4 Devices & Environment", guideQ4Desc: "Core device mix and practical constraints",
        guideFlowTitle: "Simple input, clearer output",
        guideFlowStep: "One question opens at a time.",
        guideFlowLean: "Extra checks appear only when needed.",
        guideFlowClear: "Assumptions stay separated for faster review.",
        guideNote: "If this is clear, press Start below and move into Q1. Keep the input short and the output ready to review.",
        personaTask: "Core task", personaSuccess: "Expected result",
        stateRole: "Work Lens", stateCountry: "Country", statePersona: "Target User",
        stateSituation: "Situation", stateDevice: "Device",
        notSelected: "Not selected", notEntered: "Not entered",
        guideSessionNote: "Logout ends the current session and returns to the access code screen.",
        nudgeNow: "Now", nudgeNeed: "Likely need", nudgeOpportunity: "Opportunity",
        q3AutoBtn: "Auto-configure by regional trends — AI selects the best target segment for your country and city",
        q4AutoBtn: "Auto-configure by trends — AI selects optimal devices for your region and segment",
        q4PresetTitle: "Device style presets",
        q4DirectTitle: "Select devices directly",
        q4DetailSummary: "View devices by category",
        q4SummaryTitle: "Current mix summary"
    },
    de: {
        enterAgent: "Agent Starten",
        heroEyebrow: "Interaktiver Szenario-Builder",
        heroText: "Beantworten Sie die Fragen der Reihe nach und bauen Sie schrittweise ein App-Szenario auf, das für Nutzer attraktiver wirkt.",
        heroChip1: "Kontext zuerst",
        heroChip2: "4 Schritte",
        heroChip3: "Direkt prüfbare Ergebnisse",
        heroFlow1: "Zugang und Guide",
        heroFlow2: "Schrittweise Eingabe",
        heroFlow3: "Output und Export",
        getStarted: "Loslegen",
        guideYes: "Ja",
        guideNo: "Nein",
        guideStart: "Start",
        q3Guide: "Wählen Sie mindestens je eine Option aus A, B und C oder geben Sie eigene ein. Je konkreter die Kombination, desto schärfer das Szenario.",
        cityCustomPlaceholder: "Stadt / Bundesland / Region manuell",
        deviceCustomPlaceholder: "Zusätzliche Geräte oder Modelle eingeben",
        purposeExtraPlaceholder: "Zusätzlicher Kontext über die obigen Auswahlen hinaus",
        accessRequired: "Bitte geben Sie den Zugangscode ein.",
        accessPlaceholder: "Zugangscode eingeben",
        accessHelper: "Der Zugangscode wird serverseitig geprüft und erzeugt bei Erfolg eine Sitzung.",
        accessVerifying: "Der Zugangscode wird geprüft.",
        accessInvalid: "Der Zugangscode ist ungültig.",
        accessInvalidRemaining: "Der Zugangscode ist ungültig. Verbleibende Versuche: {count}.",
        accessLocked: "Zu viele Fehlversuche. Bitte versuchen Sie es später erneut.",
        accessLockedWithTime: "Zu viele Fehlversuche. Bitte versuchen Sie es in {time} erneut.",
        accessLockedNewWindow: "Dieser Tab ist nach 3 Fehlversuchen gesperrt. Versuchen Sie es in {time} erneut oder starten Sie in einem neuen Tab.",
        accessUnavailable: "Der Verifizierungsserver ist nicht erreichbar.",
        accessGranted: "Zugang bestätigt. Die Anleitung wird geöffnet.",
        accessShow: "Anzeigen",
        accessHide: "Ausblenden",
        logout: "Abmelden",
        loggedOut: "Ihre Sitzung wurde beendet. Bitte geben Sie den Zugangscode erneut ein.",
        guideTitle: "Kennen Sie die Nutzung dieses Agents?",
        guideQuick: "Kurzanleitung",
        guideLine1: "Die Fragen erscheinen nacheinander.",
        guideLine2: "Nach jeder Antwort erhalten Sie einen kurzen Hinweis für die nächste Richtung.",
        guideLine3: "Nach vier Schritten wird sofort ein nutzbares Szenario erstellt.",
        startAfterGuide: "Gut. Wir starten jetzt Schritt für Schritt mit Q1 und geben nach jeder Antwort einen kurzen Hinweis für die nächste Richtung.",
        unlockedPlaceholder: "Nach der kurzen Nutzungsabfrage starten Sie nacheinander mit Q1.",
        stateMissing: "Ihre aktuellen Eingaben werden hier während der Fragen zusammengefasst.",
        checkPlaceholder: "Nach der Generierung erscheint hier eine kurze Strukturprüfung.",
        outputPlaceholder: "Nach Zugang und vier Fragen sehen Sie das detaillierte Szenario und die rollenspezifischen Nutzungsideen.",
        progress1: "Q1 Perspektive",
        progress2: "Q2 Region",
        progress3: "Q3 Nutzer & Kontext",
        progress4: "Q4 Gerät",
        prev: "Zurück",
        next: "Weiter",
        build: "Szenario Erstellen",
        downloadMarkdown: "Markdown Laden",
        downloadJson: "JSON Laden",
        printPdf: "Drucken / PDF Speichern",
        copySummary: "Zusammenfassung Kopieren",
        current: "Aktuelle Eingabe",
        check: "Strukturprüfung",
        output: "Szenario-Ausgabe",
        roleQuestion: "Q1. Aus welcher fachlichen Perspektive möchten Sie dieses Szenario erstellen?",
        countryQuestion: "Q2. Für welches Land ist das Szenario gedacht?",
        personaQuestion: "Q3. Welchen Nutzertyp und welche Situation haben Sie im Kopf?",
        deviceQuestion: "Q4. Welches Gerät soll im Zentrum stehen?",
        purposePlaceholder: "Beispiel: Eine Doppelverdiener-Familie möchte den Abend nach der Rückkehr mit ihrem Kind schneller und angenehmer beginnen.",
        countryHelper: "Wählen Sie zuerst Markt und Region, damit klarer wird, welcher Alltagsmoment am stärksten wirkt.",
        personaHelper: "Kombinieren Sie Haushaltstyp und Lebenskontext, damit Zielgruppe und Szenarioton präziser werden.",
        deviceHelper: "Starten Sie mit einer Oberkategorie und grenzen Sie dann die konkrete Gerätekombination ein.",
        roleMissing: "Bitte wählen Sie zuerst in Q1 die fachliche Perspektive aus.",
        countryMissing: "Bitte wählen Sie in Q2 das Land aus.",
        personaMissing: "Wählen Sie in Q3 den Nutzertyp oder beschreiben Sie die Situation.",
        allMissing: "Bitte beantworten Sie zuerst alle vier Fragen.",
        downloadFirst: "Bitte erzeugen Sie zuerst ein Szenario.",
        summaryState: "Eingabeübersicht",
        detailedScenario: "Detailliertes Szenario",
        automation: "Automationsablauf",
        facts: "Grundlage des Szenarios",
        confirmed: "Bestätigte Informationen",
        assumptions: "Hinweise",
        lenses: "Nutzung nach Rolle",
        effects: "Erwartete Wirkung",
        segment: "Empfohlene Zielgruppe",
        guide: "Erste Schritte",
        evaluation: "Bewertung",
        why: "Warum",
        comparison: "Vergleich",
        note: "Hinweis",
        roleLens: "Rollenansicht",
        executionPoints: "Umsetzungspunkte",
        summary: "Zusammenfassung",
        fit: "Passend",
        review: "Überprüfen",
        fitCheck: "Szenario-Fit",
        availabilityCheck: "Geräteverfügbarkeit",
        executionCheck: "Umsetzbarkeit",
        clarityCheck: "Botschaftsklarheit",
        metricCheck: "Wirkungsbezug",
        previewTitle: "Schließen Sie Q1–Q4 ab und erhalten Sie Ihre Ergebnisse in dieser Struktur.",
        prev01Title: "Szenario-Zusammenfassung", prev01Desc: "Zielkunde und Kernwertversprechen auf einen Blick.",
        prev02Title: "Detailliertes Szenario", prev02Desc: "Zielkunde, Dienste und Szenario-Karten mit Problem, Lösung und Nutzen.",
        prev03Title: "Lokaler Einblick", prev03Desc: "Warum dieses Szenario in diesem Markt funktioniert — Beobachtung, Einsicht, Implikation.",
        prev04Title: "Marketing-Botschaften", prev04Desc: "Kampagnentaugliche Textoptionen passend zur gewählten Rolle vergleichen.",
        prev05Title: "Kundenvorteile", prev05Desc: "Die überzeugendsten Nutzervorteile priorisieren.",
        prev06Title: "Zielgruppe & Akzeptanz", prev06Desc: "Erwartete Zustimmung, Bedenken und Akzeptanz vor der Umsetzung einschätzen.",
        prev07Title: "Timing & Kreativrichtung", prev07Desc: "Das Szenario mit dem Kampagnenzeitpunkt und der Story-Richtung verbinden.",
        exportPdf: "PDF speichern", exportPdfDesc: "Für Meetings & E-Mail-Anhänge",
        exportWord: "Word speichern", exportWordDesc: "Bearbeitbares Dokument zur Zusammenarbeit",
        exportExcel: "Excel speichern", exportExcelDesc: "Strukturierte Datentabellen",
        exportCopy: "In Zwischenablage", exportCopyDesc: "Schnell einfügen & teilen",
        outputLabel: "Output", outputTitle: "Szenario-Ausgabe",
        outTitle01: "01. Titel & Zusammenfassung",
        outTitle02: "02. Detailliertes Szenario",
        outTitle03: "03. Lokaler Einblick",
        outTitle04: "04. Marketing-Botschaften",
        outTitle05: "05. Kundenvorteile",
        outTitle06: "06. Zielgruppe & Akzeptanz",
        outTitle07: "07. Timing & Kreativrichtung",
        outTitle08: "08. Verfügbare Geräte & Einrichtung",
        outTitle09: "09. Marktfähigkeit & Risikobewertung",
        outTitle10: "10. Erweiterungspaket — Umsetzung & Funnel-Zuordnung",
        outTitle11: "11. Marke/KI/Philosophie — Reflexion",
        guideHeroTitle: "Erstellen Sie ein nutzbares Szenario<br>aus vier geführten Eingaben",
        guideLead: "Wählen Sie das Wesentliche. Der Agent macht daraus ein schärferes, prüfbereites Szenario.",
        guideInputsTitle: "Was Sie zuerst festlegen",
        guideQ1: "Q1 Perspektive", guideQ1Desc: "Retail, Dotcom-Kampagne oder Markenmarketing",
        guideQ2: "Q2 Land & Region", guideQ2Desc: "Zielmarkt plus Stadt, Bundesland oder Region",
        guideQ3: "Q3 Zielkunde", guideQ3Desc: "Haushaltstyp, Saison und Lebenskontext",
        guideQ4: "Q4 Geräte & Umgebung", guideQ4Desc: "Kerngerätemix und praktische Einschränkungen",
        guideFlowTitle: "Einfache Eingabe, klareres Ergebnis",
        guideFlowStep: "Eine Frage wird gleichzeitig geöffnet.",
        guideFlowLean: "Zusätzliche Prüfungen erscheinen nur bei Bedarf.",
        guideFlowClear: "Annahmen werden getrennt für eine schnellere Überprüfung.",
        guideNote: "Wenn alles klar ist, drücken Sie unten Start und beginnen Sie mit Q1. Halten Sie die Eingabe kurz — das Ergebnis ist sofort prüfbereit.",
        personaTask: "Zentrale Aufgabe", personaSuccess: "Erwartetes Ergebnis",
        stateRole: "Perspektive", stateCountry: "Land", statePersona: "Zielnutzer",
        stateSituation: "Situation", stateDevice: "Gerät",
        notSelected: "Nicht gewählt", notEntered: "Nicht eingegeben",
        guideSessionNote: "Abmelden beendet die aktuelle Sitzung und kehrt zum Zugangscode-Bildschirm zurück.",
        nudgeNow: "Aktuell", nudgeNeed: "Wahrscheinlicher Bedarf", nudgeOpportunity: "Chance",
        q3AutoBtn: "Automatische Konfiguration nach regionalen Trends — KI wählt das beste Zielsegment",
        q4AutoBtn: "Automatische Konfiguration — KI wählt optimale Geräte für Ihre Region",
        q4PresetTitle: "Geräte-Stilpresets", q4DirectTitle: "Geräte direkt auswählen",
        q4DetailSummary: "Geräte nach Kategorie anzeigen", q4SummaryTitle: "Aktuelle Zusammenfassung"
    },
    fr: {
        enterAgent: "Entrer dans l'agent",
        accessRequired: "Veuillez saisir le code d'accès.",
        accessPlaceholder: "Saisir le code d'accès",
        accessHelper: "Le code d'accès est vérifié sur le serveur et ouvre immédiatement l'étape suivante après validation.",
        guideTitle: "Savez-vous comment utiliser cet agent ?",
        guideQuick: "Guide Rapide",
        guideLine1: "Les questions apparaissent une par une.",
        guideLine2: "Après chaque réponse, vous recevez un court indice pour orienter la suite.",
        guideLine3: "Une fois les quatre étapes terminées, un scénario exploitable est généré immédiatement.",
        startAfterGuide: "Très bien. Nous allons commencer à partir de la Q1, étape par étape, avec un court indice après chaque réponse.",
        unlockedPlaceholder: "Après cette vérification rapide, vous commencerez à partir de la Q1.",
        stateMissing: "Vos sélections actuelles apparaîtront ici au fur et à mesure.",
        checkPlaceholder: "Une vérification rapide de la structure apparaîtra après la génération du scénario.",
        outputPlaceholder: "Après l'accès et les quatre questions, vous verrez le scénario détaillé et les applications par rôle.",
        progress1: "Q1 Rôle",
        progress2: "Q2 Région",
        progress3: "Q3 Utilisateur et contexte",
        progress4: "Q4 Appareil",
        prev: "Précédent",
        next: "Suivant",
        build: "Créer le scénario",
        downloadMarkdown: "Télécharger Markdown",
        downloadJson: "Télécharger JSON",
        printPdf: "Imprimer / Enregistrer PDF",
        copySummary: "Copier le résumé",
        current: "Entrée actuelle",
        check: "Vérification",
        output: "Sortie du scénario",
        roleQuestion: "Q1. Sous quel angle professionnel souhaitez-vous construire ce scénario ?",
        countryQuestion: "Q2. Pour quel pays ce scénario est-il destiné ?",
        personaQuestion: "Q3. Quel utilisateur et quelle situation avez-vous en tête ?",
        deviceQuestion: "Q4. Quel appareil doit être au centre du scénario ?",
        purposePlaceholder: "Exemple : une famille avec deux revenus souhaite commencer la soirée plus vite et plus confortablement après son retour à la maison avec son enfant.",
        countryHelper: "Les appareils recommandés et les angles narratifs peuvent varier selon le marché.",
        personaHelper: "Ajoutez l'âge, le mode de vie, la saison et les problèmes à la maison pour rendre le scénario plus convaincant.",
        deviceHelper: "Choisir une catégorie d'appareil rend le scénario plus flexible et évolutif.",
        roleMissing: "Veuillez d'abord choisir l'angle professionnel dans la Q1.",
        countryMissing: "Veuillez choisir le pays dans la Q2.",
        personaMissing: "Dans la Q3, sélectionnez le type d'utilisateur ou décrivez la situation.",
        allMissing: "Veuillez compléter les quatre questions avant de générer le scénario.",
        downloadFirst: "Veuillez d'abord générer un scénario.",
        summaryState: "Résumé des entrées",
        detailedScenario: "Scénario détaillé",
        automation: "Flux d'automatisation",
        facts: "Base du scénario",
        confirmed: "Informations confirmées",
        assumptions: "Notes",
        lenses: "Usages par rôle",
        effects: "Impact attendu",
        segment: "Public recommandé",
        guide: "Premiers pas",
        evaluation: "Évaluation",
        why: "Pourquoi",
        comparison: "Comparaison",
        note: "Note",
        roleLens: "Vue par rôle",
        executionPoints: "Points d'exécution",
        summary: "Résumé",
        fit: "Bon",
        review: "À revoir",
        fitCheck: "Pertinence du scénario",
        availabilityCheck: "Disponibilité de l'appareil",
        executionCheck: "Faisabilité",
        clarityCheck: "Clarté du message",
        metricCheck: "Lien avec le résultat",
        heroEyebrow: "Interactive Scenario Builder",
        heroText: "Répondez aux questions dans l'ordre et construisez pas à pas un scénario plus convaincant pour les utilisateurs.",
        heroChip1: "Conception contextuelle",
        heroChip2: "4 étapes guidées",
        heroChip3: "Résultat prêt à l'emploi",
        heroFlow1: "Vérification d'accès et guide",
        heroFlow2: "Configuration étape par étape",
        heroFlow3: "Résultat et export immédiats",
        getStarted: "Commencer",
        q3Guide: "Choisissez au moins un élément dans A, B et C (ou saisissez-le). Plus la combinaison est précise, plus le scénario est percutant.",
        cityCustomPlaceholder: "Saisir ville / état / région",
        deviceCustomPlaceholder: "Appareil ou modèle supplémentaire",
        purposeExtraPlaceholder: "Tout contexte supplémentaire au-delà des sélections ci-dessus",
        accessVerifying: "Vérification du code d'accès en cours.",
        accessInvalid: "Code d'accès invalide.",
        accessInvalidRemaining: "Code d'accès invalide. {count} tentatives restantes.",
        accessLocked: "Trop de tentatives échouées. Réessayez plus tard.",
        accessLockedWithTime: "Trop de tentatives échouées. Réessayez dans {time}.",
        accessLockedNewWindow: "Cet onglet est verrouillé après 3 échecs. Réessayez dans {time} ou ouvrez un nouvel onglet.",
        accessUnavailable: "Le serveur de vérification n'est pas disponible.",
        accessGranted: "Accès confirmé. Ouverture du guide.",
        accessShow: "Afficher",
        accessHide: "Masquer",
        logout: "Déconnexion",
        loggedOut: "Session terminée. Veuillez saisir à nouveau le code d'accès.",
        previewTitle: "Complétez Q1–Q4 et recevez vos résultats dans cette structure.",
        prev01Title: "Résumé du scénario", prev01Desc: "Client cible et proposition de valeur en un coup d'œil.",
        prev02Title: "Scénario détaillé", prev02Desc: "Client cible, services et cartes scénario avec problème, solution et bénéfice.",
        prev03Title: "Insight local", prev03Desc: "Pourquoi ce scénario fonctionne sur ce marché — Observation, Insight, Implication.",
        prev04Title: "Messages marketing", prev04Desc: "Comparez les options de texte adaptées au rôle choisi.",
        prev05Title: "Bénéfices client", prev05Desc: "Priorisez les avantages utilisateur les plus convaincants.",
        prev06Title: "Cible et acceptation", prev06Desc: "Estimez la réception, les préoccupations et l'acceptation avant l'exécution.",
        prev07Title: "Timing et direction créative", prev07Desc: "Reliez le scénario au timing de campagne et à la direction narrative.",
        exportPdf: "Enregistrer PDF", exportPdfDesc: "Pour réunions et pièces jointes",
        exportWord: "Enregistrer Word", exportWordDesc: "Document modifiable pour la collaboration",
        exportExcel: "Enregistrer Excel", exportExcelDesc: "Tableaux de données structurées",
        exportCopy: "Copier", exportCopyDesc: "Coller et partager rapidement",
        outputLabel: "Output", outputTitle: "Sortie du scénario",
        outTitle01: "01. Titre et résumé",
        outTitle02: "02. Scénario détaillé",
        outTitle03: "03. Insight local",
        outTitle04: "04. Messages marketing",
        outTitle05: "05. Bénéfices client",
        outTitle06: "06. Cible et acceptation",
        outTitle07: "07. Timing et direction créative",
        outTitle08: "08. Appareils disponibles et guide de configuration",
        outTitle09: "09. Évaluation de la commercialisation et des risques",
        outTitle10: "10. Pack d'extension — Mise en œuvre et cartographie de l'entonnoir",
        outTitle11: "11. Réflexion Marque/IA/Philosophie",
        guideHeroTitle: "Construisez un scénario exploitable<br>à partir de quatre entrées guidées",
        guideLead: "Choisissez l'essentiel d'abord. L'agent le transforme en un scénario plus précis et prêt à l'emploi.",
        guideInputsTitle: "Ce que vous définissez d'abord",
        guideQ1: "Q1 Rôle", guideQ1Desc: "Retail, Campagne Dotcom ou Marketing de marque",
        guideQ2: "Q2 Pays et région", guideQ2Desc: "Marché cible plus ville, état ou région",
        guideQ3: "Q3 Client cible", guideQ3Desc: "Type de ménage, saison et contexte de vie",
        guideQ4: "Q4 Appareils et environnement", guideQ4Desc: "Mix d'appareils et contraintes pratiques",
        guideFlowTitle: "Entrée simple, résultat plus clair",
        guideFlowStep: "Une question à la fois.",
        guideFlowLean: "Les vérifications supplémentaires n'apparaissent qu'en cas de besoin.",
        guideFlowClear: "Les hypothèses restent séparées pour une révision plus rapide.",
        guideNote: "Si c'est clair, appuyez sur Démarrer ci-dessous et passez à la Q1. Gardez l'entrée courte — le résultat est prêt à réviser.",
        personaTask: "Tâche principale", personaSuccess: "Résultat attendu",
        stateRole: "Rôle", stateCountry: "Pays", statePersona: "Utilisateur cible",
        stateSituation: "Situation", stateDevice: "Appareil",
        notSelected: "Non sélectionné", notEntered: "Non saisi",
        guideSessionNote: "La déconnexion met fin à la session et retourne à l'écran du code d'accès.",
        nudgeNow: "Situation actuelle", nudgeNeed: "Besoin probable", nudgeOpportunity: "Opportunité",
        q3AutoBtn: "Configuration auto par tendances régionales — l'IA sélectionne le meilleur segment cible",
        q4AutoBtn: "Configuration auto — l'IA sélectionne les appareils optimaux pour votre région",
        q4PresetTitle: "Préréglages par style", q4DirectTitle: "Sélection directe",
        q4DetailSummary: "Voir par catégorie", q4SummaryTitle: "Résumé actuel"
    },
    es: {
        enterAgent: "Entrar al agente",
        accessRequired: "Por favor, introduce el código de acceso.",
        accessPlaceholder: "Introducir código de acceso",
        accessHelper: "El código de acceso se verifica en el servidor y te lleva al siguiente paso en cuanto se aprueba.",
        guideTitle: "¿Sabes cómo usar este agente?",
        guideQuick: "Guía Rápida",
        guideLine1: "Las preguntas aparecen una por una.",
        guideLine2: "Después de cada respuesta, recibirás una pista breve para orientar el siguiente paso.",
        guideLine3: "Cuando completes los cuatro pasos, se generará de inmediato un escenario utilizable.",
        startAfterGuide: "Bien. Empezaremos desde la Q1 paso a paso, con una pista breve después de cada respuesta.",
        unlockedPlaceholder: "Después de esta breve verificación, comenzarás desde la Q1.",
        stateMissing: "Tus selecciones actuales aparecerán aquí a medida que respondas.",
        checkPlaceholder: "Aquí aparecerá una revisión rápida de la estructura después de generar el escenario.",
        outputPlaceholder: "Después del acceso y de responder las cuatro preguntas, verás el escenario detallado y las aplicaciones por rol.",
        progress1: "Q1 Enfoque",
        progress2: "Q2 Región",
        progress3: "Q3 Usuario y contexto",
        progress4: "Q4 Dispositivo",
        prev: "Atrás",
        next: "Siguiente",
        build: "Crear escenario",
        downloadMarkdown: "Descargar Markdown",
        downloadJson: "Descargar JSON",
        printPdf: "Imprimir / Guardar PDF",
        copySummary: "Copiar resumen",
        current: "Entrada actual",
        check: "Revisión",
        output: "Resultado del escenario",
        roleQuestion: "Q1. ¿Desde qué perspectiva profesional quieres crear este escenario?",
        countryQuestion: "Q2. ¿Para qué país es este escenario?",
        personaQuestion: "Q3. ¿Qué usuario y qué situación tienes en mente?",
        deviceQuestion: "Q4. ¿Qué dispositivo debe ser el eje del escenario?",
        purposePlaceholder: "Ejemplo: una familia con doble ingreso quiere empezar la noche de forma más rápida y cómoda al llegar a casa con su hijo.",
        countryHelper: "Los dispositivos recomendados y los enfoques narrativos pueden variar según el mercado.",
        personaHelper: "Añade edad, estilo de vida, temporada y problemas del hogar para que el escenario sea más convincente.",
        deviceHelper: "Elegir una categoría de dispositivo hace que el escenario sea más flexible y ampliable.",
        roleMissing: "Primero elige la perspectiva profesional en la Q1.",
        countryMissing: "Elige el país en la Q2.",
        personaMissing: "En la Q3, selecciona el tipo de usuario o describe la situación.",
        allMissing: "Completa las cuatro preguntas antes de generar el escenario.",
        downloadFirst: "Primero genera un escenario.",
        summaryState: "Resumen de entrada",
        detailedScenario: "Escenario detallado",
        automation: "Flujo de automatización",
        facts: "Base del escenario",
        confirmed: "Información confirmada",
        assumptions: "Notas",
        lenses: "Usos por rol",
        effects: "Impacto esperado",
        segment: "Audiencia recomendada",
        guide: "Primeros pasos",
        evaluation: "Evaluación",
        why: "Por qué",
        comparison: "Comparación",
        note: "Nota",
        roleLens: "Vista por rol",
        executionPoints: "Puntos de ejecución",
        summary: "Resumen",
        fit: "Adecuado",
        review: "Revisar",
        fitCheck: "Ajuste del escenario",
        availabilityCheck: "Disponibilidad del dispositivo",
        executionCheck: "Viabilidad",
        clarityCheck: "Claridad del mensaje",
        metricCheck: "Vínculo con el resultado",
        heroEyebrow: "Interactive Scenario Builder",
        heroText: "Responde las preguntas en orden y construye paso a paso un escenario más convincente para los usuarios.",
        heroChip1: "Diseño contextual",
        heroChip2: "4 pasos guiados",
        heroChip3: "Resultado listo para revisar",
        heroFlow1: "Verificación de acceso y guía",
        heroFlow2: "Configuración paso a paso",
        heroFlow3: "Resultado y exportación inmediatos",
        getStarted: "Comenzar",
        q3Guide: "Elige al menos uno de A, B y C (o escríbelo). Cuanto más específica la combinación, más preciso el escenario.",
        cityCustomPlaceholder: "Escribe ciudad / estado / región",
        deviceCustomPlaceholder: "Dispositivo o modelo adicional",
        purposeExtraPlaceholder: "Cualquier contexto adicional más allá de las selecciones anteriores",
        accessVerifying: "Verificando el código de acceso.",
        accessInvalid: "Código de acceso no válido.",
        accessInvalidRemaining: "Código de acceso no válido. {count} intentos restantes.",
        accessLocked: "Demasiados intentos fallidos. Inténtalo más tarde.",
        accessLockedWithTime: "Demasiados intentos fallidos. Inténtalo de nuevo en {time}.",
        accessLockedNewWindow: "Esta pestaña está bloqueada tras 3 intentos fallidos. Inténtalo en {time} o abre una nueva pestaña.",
        accessUnavailable: "El servidor de verificación no está disponible.",
        accessGranted: "Acceso confirmado. Abriendo la guía.",
        accessShow: "Mostrar",
        accessHide: "Ocultar",
        logout: "Cerrar sesión",
        loggedOut: "Sesión finalizada. Introduce el código de acceso de nuevo.",
        previewTitle: "Completa Q1–Q4 y recibirás tus resultados con esta estructura.",
        prev01Title: "Resumen del escenario", prev01Desc: "Cliente objetivo y propuesta de valor de un vistazo.",
        prev02Title: "Escenario detallado", prev02Desc: "Cliente objetivo, servicios y tarjetas de escenario con problema, solución y beneficio.",
        prev03Title: "Insight local", prev03Desc: "Por qué este escenario funciona en este mercado — Observación, Insight, Implicación.",
        prev04Title: "Mensajes de marketing", prev04Desc: "Compara opciones de texto adaptadas al rol seleccionado.",
        prev05Title: "Beneficios para el cliente", prev05Desc: "Prioriza los beneficios más convincentes para el usuario.",
        prev06Title: "Público y aceptación", prev06Desc: "Estima la aceptación, las preocupaciones y la recepción antes de la ejecución.",
        prev07Title: "Timing y dirección creativa", prev07Desc: "Conecta el escenario con el timing de campaña y la dirección narrativa.",
        exportPdf: "Guardar PDF", exportPdfDesc: "Para reuniones y adjuntos de correo",
        exportWord: "Guardar Word", exportWordDesc: "Documento editable para colaboración",
        exportExcel: "Guardar Excel", exportExcelDesc: "Tablas de datos estructurados",
        exportCopy: "Copiar al portapapeles", exportCopyDesc: "Pegar y compartir rápidamente",
        outputLabel: "Output", outputTitle: "Resultado del escenario",
        outTitle01: "01. Título y resumen",
        outTitle02: "02. Escenario detallado",
        outTitle03: "03. Insight local",
        outTitle04: "04. Mensajes de marketing",
        outTitle05: "05. Beneficios para el cliente",
        outTitle06: "06. Público objetivo y aceptación",
        outTitle07: "07. Timing y dirección creativa",
        outTitle08: "08. Dispositivos disponibles y guía de configuración",
        outTitle09: "09. Evaluación de comercialización y riesgos",
        outTitle10: "10. Pack de extensión — Implementación y mapeo del embudo",
        outTitle11: "11. Reflexión Marca/IA/Filosofía",
        guideHeroTitle: "Construye un escenario útil<br>a partir de cuatro entradas guiadas",
        guideLead: "Elige lo esencial primero. El agente lo convierte en un escenario más preciso y listo para revisar.",
        guideInputsTitle: "Lo que defines primero",
        guideQ1: "Q1 Enfoque", guideQ1Desc: "Retail, Campaña Dotcom o Marketing de marca",
        guideQ2: "Q2 País y región", guideQ2Desc: "Mercado objetivo más ciudad, estado o región",
        guideQ3: "Q3 Cliente objetivo", guideQ3Desc: "Tipo de hogar, temporada y contexto de vida",
        guideQ4: "Q4 Dispositivos y entorno", guideQ4Desc: "Combinación de dispositivos y restricciones prácticas",
        guideFlowTitle: "Entrada simple, resultado más claro",
        guideFlowStep: "Una pregunta a la vez.",
        guideFlowLean: "Las comprobaciones adicionales aparecen solo cuando es necesario.",
        guideFlowClear: "Las suposiciones se separan para una revisión más rápida.",
        guideNote: "Si está claro, pulsa Iniciar abajo y pasa a la Q1. Mantén la entrada breve — el resultado estará listo para revisar.",
        personaTask: "Tarea principal", personaSuccess: "Resultado esperado",
        stateRole: "Enfoque", stateCountry: "País", statePersona: "Usuario objetivo",
        stateSituation: "Situación", stateDevice: "Dispositivo",
        notSelected: "No seleccionado", notEntered: "No ingresado",
        guideSessionNote: "Cerrar sesión finaliza la sesión actual y vuelve a la pantalla del código de acceso.",
        nudgeNow: "Situación actual", nudgeNeed: "Necesidad probable", nudgeOpportunity: "Oportunidad",
        q3AutoBtn: "Configuración automática por tendencias — la IA selecciona el mejor segmento objetivo",
        q4AutoBtn: "Configuración automática — la IA selecciona los dispositivos óptimos para su región",
        q4PresetTitle: "Presets por estilo", q4DirectTitle: "Selección directa",
        q4DetailSummary: "Ver por categoría", q4SummaryTitle: "Resumen actual"
    },
    pt: {
        enterAgent: "Entrar no agente",
        accessRequired: "Insira o código de acesso.",
        accessPlaceholder: "Inserir código de acesso",
        accessHelper: "O código de acesso é verificado no servidor e, quando aprovado, você segue direto para a próxima etapa.",
        guideTitle: "Você sabe como usar este agente?",
        guideQuick: "Guia Rápido",
        guideLine1: "As perguntas aparecem uma de cada vez.",
        guideLine2: "Após cada resposta, você recebe uma dica curta para orientar o próximo passo.",
        guideLine3: "Depois de concluir as quatro etapas, um cenário utilizável é gerado imediatamente.",
        startAfterGuide: "Ótimo. Vamos começar pela Q1 passo a passo, com uma dica curta após cada resposta.",
        unlockedPlaceholder: "Após esta verificação rápida, você começará pela Q1.",
        stateMissing: "Suas seleções atuais aparecerão aqui conforme você responder.",
        checkPlaceholder: "Uma verificação rápida da estrutura aparecerá aqui após a geração do cenário.",
        outputPlaceholder: "Após o acesso e as quatro perguntas, você verá o cenário detalhado e as aplicações por função.",
        progress1: "Q1 Função",
        progress2: "Q2 Região",
        progress3: "Q3 Usuário e contexto",
        progress4: "Q4 Dispositivo",
        prev: "Voltar",
        next: "Próximo",
        build: "Criar cenário",
        downloadMarkdown: "Baixar Markdown",
        downloadJson: "Baixar JSON",
        printPdf: "Imprimir / Salvar PDF",
        copySummary: "Copiar resumo",
        current: "Entrada atual",
        check: "Verificação",
        output: "Saída do cenário",
        roleQuestion: "Q1. De qual perspectiva profissional você quer construir este cenário?",
        countryQuestion: "Q2. Para qual país este cenário é destinado?",
        personaQuestion: "Q3. Que usuário e situação você tem em mente?",
        deviceQuestion: "Q4. Qual dispositivo deve estar no centro do cenário?",
        purposePlaceholder: "Exemplo: uma família com dupla renda quer começar a noite de forma mais rápida e confortável ao chegar em casa com o filho.",
        countryHelper: "Os dispositivos recomendados e os ângulos de narrativa podem variar conforme o mercado.",
        personaHelper: "Adicione idade, estilo de vida, estação e problemas em casa para deixar o cenário mais convincente.",
        deviceHelper: "Escolher uma categoria de dispositivo mantém o cenário mais flexível e expansível.",
        roleMissing: "Primeiro escolha a perspectiva profissional na Q1.",
        countryMissing: "Escolha o país na Q2.",
        personaMissing: "Na Q3, selecione o tipo de usuário ou descreva a situação.",
        allMissing: "Conclua as quatro perguntas antes de gerar o cenário.",
        downloadFirst: "Gere um cenário primeiro.",
        summaryState: "Resumo da entrada",
        detailedScenario: "Cenário detalhado",
        automation: "Fluxo de automação",
        facts: "Base do cenário",
        confirmed: "Informações confirmadas",
        assumptions: "Notas",
        lenses: "Usos por função",
        effects: "Impacto esperado",
        segment: "Público recomendado",
        guide: "Primeiros passos",
        evaluation: "Avaliação",
        why: "Por quê",
        comparison: "Comparação",
        note: "Nota",
        roleLens: "Visão por função",
        executionPoints: "Pontos de execução",
        summary: "Resumo",
        fit: "Adequado",
        review: "Revisar",
        fitCheck: "Adequação do cenário",
        availabilityCheck: "Disponibilidade do dispositivo",
        executionCheck: "Viabilidade",
        clarityCheck: "Clareza da mensagem",
        metricCheck: "Ligação com o resultado",
        heroEyebrow: "Interactive Scenario Builder",
        heroText: "Responda às perguntas em sequência e construa passo a passo um cenário mais convincente para os utilizadores.",
        heroChip1: "Design contextual",
        heroChip2: "4 etapas guiadas",
        heroChip3: "Resultado pronto para revisão",
        heroFlow1: "Verificação de acesso e guia",
        heroFlow2: "Configuração passo a passo",
        heroFlow3: "Resultado e exportação imediatos",
        getStarted: "Começar",
        q3Guide: "Escolha pelo menos um de A, B e C (ou digite). Quanto mais específica a combinação, mais preciso o cenário.",
        cityCustomPlaceholder: "Digite cidade / estado / região",
        deviceCustomPlaceholder: "Dispositivo ou modelo adicional",
        purposeExtraPlaceholder: "Qualquer contexto adicional além das seleções acima",
        accessVerifying: "A verificar o código de acesso.",
        accessInvalid: "Código de acesso inválido.",
        accessInvalidRemaining: "Código de acesso inválido. {count} tentativas restantes.",
        accessLocked: "Demasiadas tentativas falhadas. Tente novamente mais tarde.",
        accessLockedWithTime: "Demasiadas tentativas falhadas. Tente novamente em {time}.",
        accessLockedNewWindow: "Este separador está bloqueado após 3 tentativas. Tente em {time} ou abra um novo separador.",
        accessUnavailable: "Servidor de verificação indisponível.",
        accessGranted: "Acesso confirmado. A abrir o guia.",
        accessShow: "Mostrar",
        accessHide: "Ocultar",
        logout: "Sair",
        loggedOut: "Sessão terminada. Introduza o código de acesso novamente.",
        previewTitle: "Complete Q1–Q4 e receba os seus resultados nesta estrutura.",
        prev01Title: "Resumo do cenário", prev01Desc: "Cliente-alvo e proposta de valor de relance.",
        prev02Title: "Cenário detalhado", prev02Desc: "Cliente-alvo, serviços e cartões de cenário com problema, solução e benefício.",
        prev03Title: "Insight local", prev03Desc: "Porque funciona neste mercado — Observação, Insight, Implicação.",
        prev04Title: "Mensagens de marketing", prev04Desc: "Compare opções de texto adaptadas ao papel selecionado.",
        prev05Title: "Benefícios para o cliente", prev05Desc: "Priorize os benefícios mais convincentes para o utilizador.",
        prev06Title: "Público e aceitação", prev06Desc: "Estime a aceitação, preocupações e recetividade antes da execução.",
        prev07Title: "Timing e direção criativa", prev07Desc: "Ligue o cenário ao timing da campanha e à direção narrativa.",
        exportPdf: "Guardar PDF", exportPdfDesc: "Para reuniões e anexos de e-mail",
        exportWord: "Guardar Word", exportWordDesc: "Documento editável para colaboração",
        exportExcel: "Guardar Excel", exportExcelDesc: "Tabelas de dados estruturados",
        exportCopy: "Copiar", exportCopyDesc: "Colar e partilhar rapidamente",
        outputLabel: "Output", outputTitle: "Saída do cenário",
        outTitle01: "01. Título e resumo",
        outTitle02: "02. Cenário detalhado",
        outTitle03: "03. Insight local",
        outTitle04: "04. Mensagens de marketing",
        outTitle05: "05. Benefícios para o cliente",
        outTitle06: "06. Público-alvo e aceitação",
        outTitle07: "07. Timing e direção criativa",
        outTitle08: "08. Dispositivos disponíveis e guia de configuração",
        outTitle09: "09. Avaliação de comercialização e riscos",
        outTitle10: "10. Pack de extensão — Implementação e mapeamento do funil",
        outTitle11: "11. Reflexão Marca/IA/Filosofia",
        guideHeroTitle: "Construa um cenário utilizável<br>a partir de quatro entradas guiadas",
        guideLead: "Escolha o essencial primeiro. O agente transforma-o num cenário mais preciso e pronto para revisão.",
        guideInputsTitle: "O que define primeiro",
        guideQ1: "Q1 Função", guideQ1Desc: "Retail, Campanha Dotcom ou Marketing de marca",
        guideQ2: "Q2 País e região", guideQ2Desc: "Mercado-alvo mais cidade, estado ou região",
        guideQ3: "Q3 Cliente-alvo", guideQ3Desc: "Tipo de agregado familiar, estação e contexto de vida",
        guideQ4: "Q4 Dispositivos e ambiente", guideQ4Desc: "Combinação de dispositivos e restrições práticas",
        guideFlowTitle: "Entrada simples, resultado mais claro",
        guideFlowStep: "Uma pergunta de cada vez.",
        guideFlowLean: "Verificações adicionais aparecem apenas quando necessário.",
        guideFlowClear: "As suposições ficam separadas para uma revisão mais rápida.",
        guideNote: "Se estiver claro, pressione Iniciar abaixo e passe para a Q1. Mantenha a entrada curta — o resultado estará pronto para revisão.",
        personaTask: "Tarefa principal", personaSuccess: "Resultado esperado",
        stateRole: "Função", stateCountry: "País", statePersona: "Utilizador-alvo",
        stateSituation: "Situação", stateDevice: "Dispositivo",
        notSelected: "Não selecionado", notEntered: "Não inserido",
        guideSessionNote: "Sair termina a sessão atual e volta ao ecrã do código de acesso.",
        nudgeNow: "Situação atual", nudgeNeed: "Necessidade provável", nudgeOpportunity: "Oportunidade",
        q3AutoBtn: "Configuração automática por tendências — a IA seleciona o melhor segmento-alvo",
        q4AutoBtn: "Configuração automática — a IA seleciona os dispositivos ideais para sua região",
        q4PresetTitle: "Presets por estilo", q4DirectTitle: "Seleção direta",
        q4DetailSummary: "Ver por categoria", q4SummaryTitle: "Resumo atual"
    },
    it: {
        enterAgent: "Entra nell'agente",
        accessRequired: "Inserisci il codice di accesso.",
        accessPlaceholder: "Inserisci codice di accesso",
        accessHelper: "Il codice di accesso viene verificato sul server e, quando approvato, passa subito allo step successivo.",
        guideTitle: "Sai come usare questo agente?",
        guideQuick: "Guida Rapida",
        guideLine1: "Le domande appaiono una alla volta.",
        guideLine2: "Dopo ogni risposta ricevi un breve suggerimento per orientare il passo successivo.",
        guideLine3: "Dopo quattro passaggi viene generato subito uno scenario utilizzabile.",
        startAfterGuide: "Bene. Inizieremo dalla Q1 passo dopo passo, con un breve suggerimento dopo ogni risposta.",
        unlockedPlaceholder: "Dopo questa breve verifica inizierai dalla Q1.",
        stateMissing: "Le tue selezioni attuali appariranno qui mentre rispondi.",
        checkPlaceholder: "Qui comparirà un rapido controllo della struttura dopo la generazione dello scenario.",
        outputPlaceholder: "Dopo l'accesso e le quattro domande vedrai lo scenario dettagliato e le applicazioni per ruolo.",
        progress1: "Q1 Ruolo",
        progress2: "Q2 Regione",
        progress3: "Q3 Utente e contesto",
        progress4: "Q4 Dispositivo",
        prev: "Indietro",
        next: "Avanti",
        build: "Crea scenario",
        downloadMarkdown: "Scarica Markdown",
        downloadJson: "Scarica JSON",
        printPdf: "Stampa / Salva PDF",
        copySummary: "Copia riepilogo",
        current: "Input attuale",
        check: "Controllo",
        output: "Output scenario",
        roleQuestion: "Q1. Da quale prospettiva professionale vuoi costruire questo scenario?",
        countryQuestion: "Q2. Per quale paese è pensato questo scenario?",
        personaQuestion: "Q3. Quale utente e quale situazione hai in mente?",
        deviceQuestion: "Q4. Quale dispositivo deve stare al centro dello scenario?",
        purposePlaceholder: "Esempio: una famiglia con doppio reddito vuole iniziare la serata in modo più rapido e confortevole appena rientra a casa con il figlio.",
        countryHelper: "I dispositivi consigliati e gli angoli narrativi possono cambiare in base al mercato.",
        personaHelper: "Aggiungi età, stile di vita, stagione e problemi in casa per rendere lo scenario più convincente.",
        deviceHelper: "Scegliere una categoria di dispositivo rende lo scenario più flessibile ed estendibile.",
        roleMissing: "Per prima cosa scegli la prospettiva professionale nella Q1.",
        countryMissing: "Scegli il paese nella Q2.",
        personaMissing: "Nella Q3, seleziona il tipo di utente o descrivi la situazione.",
        allMissing: "Completa tutte e quattro le domande prima di generare lo scenario.",
        downloadFirst: "Genera prima uno scenario.",
        summaryState: "Riepilogo input",
        detailedScenario: "Scenario dettagliato",
        automation: "Flusso di automazione",
        facts: "Base dello scenario",
        confirmed: "Informazioni confermate",
        assumptions: "Note",
        lenses: "Usi per ruolo",
        effects: "Impatto atteso",
        segment: "Pubblico consigliato",
        guide: "Primi passi",
        evaluation: "Valutazione",
        why: "Perché",
        comparison: "Confronto",
        note: "Nota",
        roleLens: "Vista per ruolo",
        executionPoints: "Punti di esecuzione",
        summary: "Riepilogo",
        fit: "Adatto",
        review: "Da rivedere",
        fitCheck: "Aderenza dello scenario",
        availabilityCheck: "Disponibilità del dispositivo",
        executionCheck: "Fattibilità",
        clarityCheck: "Chiarezza del messaggio",
        metricCheck: "Collegamento al risultato",
        heroEyebrow: "Interactive Scenario Builder",
        heroText: "Rispondi alle domande in ordine e costruisci passo dopo passo uno scenario più convincente per gli utenti.",
        heroChip1: "Design contestuale",
        heroChip2: "4 passaggi guidati",
        heroChip3: "Risultato pronto per la revisione",
        heroFlow1: "Verifica accesso e guida",
        heroFlow2: "Configurazione passo dopo passo",
        heroFlow3: "Risultato ed export immediati",
        getStarted: "Inizia",
        q3Guide: "Scegli almeno uno da A, B e C (o digitalo). Più specifica è la combinazione, più preciso sarà lo scenario.",
        cityCustomPlaceholder: "Digita città / stato / regione",
        deviceCustomPlaceholder: "Dispositivo o modello aggiuntivo",
        purposeExtraPlaceholder: "Qualsiasi contesto aggiuntivo oltre le selezioni precedenti",
        accessVerifying: "Verifica del codice di accesso in corso.",
        accessInvalid: "Codice di accesso non valido.",
        accessInvalidRemaining: "Codice di accesso non valido. {count} tentativi rimanenti.",
        accessLocked: "Troppi tentativi falliti. Riprova più tardi.",
        accessLockedWithTime: "Troppi tentativi falliti. Riprova tra {time}.",
        accessLockedNewWindow: "Questa scheda è bloccata dopo 3 tentativi. Riprova tra {time} o apri una nuova scheda.",
        accessUnavailable: "Il server di verifica non è disponibile.",
        accessGranted: "Accesso confermato. Apertura della guida.",
        accessShow: "Mostra",
        accessHide: "Nascondi",
        logout: "Esci",
        loggedOut: "Sessione terminata. Inserisci nuovamente il codice di accesso.",
        previewTitle: "Completa Q1–Q4 e ricevi i risultati in questa struttura.",
        prev01Title: "Riepilogo scenario", prev01Desc: "Cliente target e proposta di valore in un colpo d'occhio.",
        prev02Title: "Scenario dettagliato", prev02Desc: "Cliente target, servizi e schede scenario con problema, soluzione e beneficio.",
        prev03Title: "Insight locale", prev03Desc: "Perché questo scenario funziona in questo mercato — Osservazione, Insight, Implicazione.",
        prev04Title: "Messaggi marketing", prev04Desc: "Confronta le opzioni di testo adatte al ruolo selezionato.",
        prev05Title: "Benefici per il cliente", prev05Desc: "Dai priorità ai vantaggi più convincenti per l'utente.",
        prev06Title: "Target e accettazione", prev06Desc: "Stima gradimento, preoccupazioni e accettazione prima dell'esecuzione.",
        prev07Title: "Timing e direzione creativa", prev07Desc: "Collega lo scenario al timing della campagna e alla direzione narrativa.",
        exportPdf: "Salva PDF", exportPdfDesc: "Per riunioni e allegati e-mail",
        exportWord: "Salva Word", exportWordDesc: "Documento modificabile per la collaborazione",
        exportExcel: "Salva Excel", exportExcelDesc: "Tabelle dati strutturate",
        exportCopy: "Copia negli appunti", exportCopyDesc: "Incolla e condividi rapidamente",
        outputLabel: "Output", outputTitle: "Output scenario",
        outTitle01: "01. Titolo e riepilogo",
        outTitle02: "02. Scenario dettagliato",
        outTitle03: "03. Insight locale",
        outTitle04: "04. Messaggi marketing",
        outTitle05: "05. Benefici per il cliente",
        outTitle06: "06. Target e accettazione",
        outTitle07: "07. Timing e direzione creativa",
        outTitle08: "08. Dispositivi disponibili e guida alla configurazione",
        outTitle09: "09. Valutazione di commercializzazione e rischi",
        outTitle10: "10. Pack di estensione — Implementazione e mappatura del funnel",
        outTitle11: "11. Riflessione Marca/IA/Filosofia",
        guideHeroTitle: "Costruisci uno scenario utilizzabile<br>da quattro input guidati",
        guideLead: "Scegli prima l'essenziale. L'agente lo trasforma in uno scenario più preciso e pronto per la revisione.",
        guideInputsTitle: "Cosa definisci prima",
        guideQ1: "Q1 Ruolo", guideQ1Desc: "Retail, Campagna Dotcom o Brand Marketing",
        guideQ2: "Q2 Paese e regione", guideQ2Desc: "Mercato target più città, stato o regione",
        guideQ3: "Q3 Cliente target", guideQ3Desc: "Tipo di nucleo familiare, stagione e contesto di vita",
        guideQ4: "Q4 Dispositivi e ambiente", guideQ4Desc: "Mix di dispositivi e vincoli pratici",
        guideFlowTitle: "Input semplice, risultato più chiaro",
        guideFlowStep: "Una domanda alla volta.",
        guideFlowLean: "I controlli aggiuntivi appaiono solo quando necessario.",
        guideFlowClear: "Le ipotesi restano separate per una revisione più rapida.",
        guideNote: "Se è chiaro, premi Inizia qui sotto e passa alla Q1. Mantieni l'input breve — il risultato sarà pronto per la revisione.",
        personaTask: "Compito principale", personaSuccess: "Risultato atteso",
        stateRole: "Ruolo", stateCountry: "Paese", statePersona: "Utente target",
        stateSituation: "Situazione", stateDevice: "Dispositivo",
        notSelected: "Non selezionato", notEntered: "Non inserito",
        guideSessionNote: "Esci termina la sessione corrente e torna alla schermata del codice di accesso.",
        nudgeNow: "Situazione attuale", nudgeNeed: "Esigenza probabile", nudgeOpportunity: "Opportunità",
        q3AutoBtn: "Configurazione automatica per tendenze — l'IA seleziona il segmento target migliore",
        q4AutoBtn: "Configurazione automatica — l'IA seleziona i dispositivi ottimali per la tua regione",
        q4PresetTitle: "Preset per stile", q4DirectTitle: "Selezione diretta",
        q4DetailSummary: "Visualizza per categoria", q4SummaryTitle: "Riepilogo attuale"
    },
    nl: {
        enterAgent: "Agent openen",
        accessRequired: "Voer de toegangscode in.",
        accessPlaceholder: "Toegangscode invoeren",
        accessHelper: "De toegangscode wordt op de server gecontroleerd en gaat na goedkeuring direct door naar de volgende stap.",
        guideTitle: "Weet je hoe je deze agent gebruikt?",
        guideQuick: "Snelle gids",
        guideLine1: "De vragen verschijnen één voor één.",
        guideLine2: "Na elk antwoord krijg je een korte hint voor de volgende richting.",
        guideLine3: "Na vier stappen wordt direct een bruikbaar scenario gegenereerd.",
        startAfterGuide: "Goed. We beginnen nu stap voor stap bij Q1, met na elk antwoord een korte hint voor de volgende richting.",
        unlockedPlaceholder: "Na deze korte controle begin je bij Q1.",
        stateMissing: "Je huidige keuzes verschijnen hier terwijl je antwoordt.",
        checkPlaceholder: "Na het genereren verschijnt hier een snelle structuurcontrole.",
        outputPlaceholder: "Na toegang en vier vragen zie je het gedetailleerde scenario en de toepassingen per rol.",
        progress1: "Q1 Rol",
        progress2: "Q2 Regio",
        progress3: "Q3 Gebruiker en context",
        progress4: "Q4 Apparaat",
        prev: "Terug",
        next: "Volgende",
        build: "Scenario maken",
        downloadMarkdown: "Markdown downloaden",
        downloadJson: "JSON downloaden",
        printPdf: "Afdrukken / PDF opslaan",
        copySummary: "Samenvatting kopiëren",
        current: "Huidige invoer",
        check: "Controle",
        output: "Scenario-uitvoer",
        roleQuestion: "Q1. Vanuit welk professioneel perspectief wil je dit scenario opbouwen?",
        countryQuestion: "Q2. Voor welk land is dit scenario bedoeld?",
        personaQuestion: "Q3. Welke gebruiker en situatie heb je in gedachten?",
        deviceQuestion: "Q4. Welk apparaat moet centraal staan?",
        purposePlaceholder: "Voorbeeld: een gezin met twee inkomens wil de avond sneller en comfortabeler starten zodra het met het kind thuiskomt.",
        countryHelper: "Aanbevolen apparaten en verhaalhoeken kunnen per markt verschillen.",
        personaHelper: "Voeg leeftijd, levensstijl, seizoen en problemen thuis toe om het scenario overtuigender te maken.",
        deviceHelper: "Een apparaatcategorie kiezen houdt het scenario flexibeler en beter uitbreidbaar.",
        roleMissing: "Kies eerst het professionele perspectief in Q1.",
        countryMissing: "Kies het land in Q2.",
        personaMissing: "Kies in Q3 het gebruikerstype of beschrijf de situatie.",
        allMissing: "Voltooi eerst alle vier de vragen.",
        downloadFirst: "Genereer eerst een scenario.",
        summaryState: "Invoeroverzicht",
        detailedScenario: "Gedetailleerd scenario",
        automation: "Automatiseringsstroom",
        facts: "Basis van het scenario",
        confirmed: "Bevestigde informatie",
        assumptions: "Notities",
        lenses: "Gebruik per rol",
        effects: "Verwachte impact",
        segment: "Aanbevolen doelgroep",
        guide: "Aan de slag",
        evaluation: "Beoordeling",
        why: "Waarom",
        comparison: "Vergelijking",
        note: "Opmerking",
        roleLens: "Rolweergave",
        executionPoints: "Uitvoeringspunten",
        summary: "Samenvatting",
        fit: "Passend",
        review: "Herzien",
        fitCheck: "Scenario-fit",
        availabilityCheck: "Beschikbaarheid apparaat",
        executionCheck: "Uitvoerbaarheid",
        clarityCheck: "Duidelijkheid boodschap",
        metricCheck: "Koppeling aan resultaat",
        heroEyebrow: "Interactive Scenario Builder",
        heroText: "Beantwoord de vragen op volgorde en bouw stap voor stap een overtuigender scenario voor gebruikers.",
        heroChip1: "Context-eerst ontwerp",
        heroChip2: "4 geleide stappen",
        heroChip3: "Direct reviewbaar resultaat",
        heroFlow1: "Toegangscontrole en gids",
        heroFlow2: "Stapsgewijze configuratie",
        heroFlow3: "Direct resultaat en export",
        getStarted: "Beginnen",
        q3Guide: "Kies minstens één uit A, B en C (of typ zelf). Hoe specifieker de combinatie, hoe scherper het scenario.",
        cityCustomPlaceholder: "Typ stad / provincie / regio",
        deviceCustomPlaceholder: "Extra apparaat of model",
        purposeExtraPlaceholder: "Eventuele extra context naast bovenstaande selecties",
        accessVerifying: "Toegangscode wordt geverifieerd.",
        accessInvalid: "Ongeldige toegangscode.",
        accessInvalidRemaining: "Ongeldige toegangscode. {count} pogingen resterend.",
        accessLocked: "Te veel mislukte pogingen. Probeer het later opnieuw.",
        accessLockedWithTime: "Te veel mislukte pogingen. Probeer het opnieuw over {time}.",
        accessLockedNewWindow: "Dit tabblad is vergrendeld na 3 pogingen. Probeer het over {time} of open een nieuw tabblad.",
        accessUnavailable: "De verificatieserver is niet beschikbaar.",
        accessGranted: "Toegang bevestigd. Gids wordt geopend.",
        accessShow: "Tonen",
        accessHide: "Verbergen",
        logout: "Uitloggen",
        loggedOut: "Sessie beëindigd. Voer de toegangscode opnieuw in.",
        previewTitle: "Voltooi Q1–Q4 en ontvang je resultaten in deze structuur.",
        prev01Title: "Scenario-samenvatting", prev01Desc: "Doelklant en kernwaardepropositie in één oogopslag.",
        prev02Title: "Gedetailleerd scenario", prev02Desc: "Doelklant, diensten en scenariokaarten met probleem, oplossing en voordeel.",
        prev03Title: "Lokaal inzicht", prev03Desc: "Waarom dit scenario werkt op deze markt — Observatie, Inzicht, Implicatie.",
        prev04Title: "Marketingboodschappen", prev04Desc: "Vergelijk tekstopties afgestemd op de gekozen rol.",
        prev05Title: "Klantvoordelen", prev05Desc: "Prioriteer de meest overtuigende gebruikersvoordelen.",
        prev06Title: "Doelgroep en acceptatie", prev06Desc: "Schat de verwachte acceptatie, zorgen en ontvangst in vóór uitvoering.",
        prev07Title: "Timing en creatieve richting", prev07Desc: "Verbind het scenario met campagnetiming en bruikbare verhaalrichting.",
        exportPdf: "PDF opslaan", exportPdfDesc: "Voor vergaderingen en e-mailbijlagen",
        exportWord: "Word opslaan", exportWordDesc: "Bewerkbaar document voor samenwerking",
        exportExcel: "Excel opslaan", exportExcelDesc: "Gestructureerde datatabellen",
        exportCopy: "Kopiëren", exportCopyDesc: "Snel plakken en delen",
        outputLabel: "Output", outputTitle: "Scenario-uitvoer",
        outTitle01: "01. Titel en samenvatting",
        outTitle02: "02. Gedetailleerd scenario",
        outTitle03: "03. Lokaal inzicht",
        outTitle04: "04. Marketingboodschappen",
        outTitle05: "05. Klantvoordelen",
        outTitle06: "06. Doelgroep en acceptatie",
        outTitle07: "07. Timing en creatieve richting",
        outTitle08: "08. Beschikbare apparaten en installatiegids",
        outTitle09: "09. Marktpotentieel en risicobeoordeling",
        outTitle10: "10. Uitbreidingspakket — Implementatie en funnelmapping",
        outTitle11: "11. Merk/AI/Filosofie — Reflectie",
        guideHeroTitle: "Bouw een bruikbaar scenario<br>uit vier geleide invoeren",
        guideLead: "Kies eerst de kern. De agent maakt er een scherper, direct reviewbaar scenario van.",
        guideInputsTitle: "Wat je eerst instelt",
        guideQ1: "Q1 Rol", guideQ1Desc: "Retail, Dotcom-campagne of Merkmarketing",
        guideQ2: "Q2 Land en regio", guideQ2Desc: "Doelmarkt plus stad, provincie of regio",
        guideQ3: "Q3 Doelklant", guideQ3Desc: "Huishoudtype, seizoen en levenssituatie",
        guideQ4: "Q4 Apparaten en omgeving", guideQ4Desc: "Kernapparatenmix en praktische beperkingen",
        guideFlowTitle: "Simpele invoer, helderder resultaat",
        guideFlowStep: "Eén vraag tegelijk.",
        guideFlowLean: "Extra controles verschijnen alleen wanneer nodig.",
        guideFlowClear: "Aannames worden gescheiden voor snellere beoordeling.",
        guideNote: "Als dit duidelijk is, druk op Start hieronder en ga naar Q1. Houd de invoer kort — het resultaat is direct reviewbaar.",
        personaTask: "Kerntaak", personaSuccess: "Verwacht resultaat",
        stateRole: "Rol", stateCountry: "Land", statePersona: "Doelgebruiker",
        stateSituation: "Situatie", stateDevice: "Apparaat",
        notSelected: "Niet geselecteerd", notEntered: "Niet ingevoerd",
        guideSessionNote: "Uitloggen beëindigt de huidige sessie en keert terug naar het toegangscode-scherm.",
        nudgeNow: "Huidige situatie", nudgeNeed: "Waarschijnlijke behoefte", nudgeOpportunity: "Kans",
        q3AutoBtn: "Automatische configuratie op basis van trends — AI selecteert het beste doelsegment",
        q4AutoBtn: "Automatische configuratie — AI selecteert optimale apparaten voor uw regio",
        q4PresetTitle: "Apparaatstijl-presets", q4DirectTitle: "Directe selectie",
        q4DetailSummary: "Per categorie bekijken", q4SummaryTitle: "Huidig overzicht"
    },
    ar: {
        enterAgent: "دخول الوكيل",
        heroEyebrow: "منشئ السيناريوهات التفاعلي",
        heroText: "أجب عن الأسئلة بالتسلسل وابنِ سيناريو تطبيقي خطوة بخطوة يبدو أكثر إقناعًا للمستخدمين.",
        heroChip1: "تصميم قائم على السياق",
        heroChip2: "4 مدخلات موجَّهة",
        heroChip3: "مخرجات جاهزة للمراجعة",
        heroFlow1: "التحقق من الوصول والدليل",
        heroFlow2: "إعداد السيناريو خطوة بخطوة",
        heroFlow3: "المخرجات والتصدير الفوري",
        getStarted: "ابدأ",
        guideYes: "نعم",
        guideNo: "لا",
        guideStart: "ابدأ",
        q3Guide: "اختر واحدًا على الأقل من كل مجموعة A وB وC (أو اكتب بنفسك). كلما كان التوليف أدقّ، كان السيناريو أحدّ.",
        cityCustomPlaceholder: "اكتب المدينة / الولاية / المنطقة",
        deviceCustomPlaceholder: "أضف أي جهاز أو طراز إضافي",
        purposeExtraPlaceholder: "أي سياق إضافي بخلاف الاختيارات أعلاه",
        accessRequired: "يرجى إدخال رمز الوصول.",
        accessPlaceholder: "أدخل رمز الوصول",
        accessHelper: "يتم التحقق من رمز الوصول على الخادم، وعند اعتماده تنتقل مباشرة إلى الخطوة التالية.",
        accessVerifying: "جارٍ التحقق من رمز الوصول.",
        accessInvalid: "رمز الوصول غير صالح.",
        accessInvalidRemaining: "رمز الوصول غير صالح. المحاولات المتبقية: {count}.",
        accessLocked: "تم القفل بسبب كثرة المحاولات الفاشلة. يرجى المحاولة لاحقاً.",
        accessLockedWithTime: "تم القفل بسبب كثرة المحاولات الفاشلة. حاول مرة أخرى بعد {time}.",
        accessLockedNewWindow: "تم القفل بعد 3 محاولات فاشلة. حاول بعد {time} أو افتح نافذة جديدة.",
        accessUnavailable: "تعذر الاتصال بخادم التحقق.",
        accessGranted: "تم تأكيد الوصول. جارٍ فتح الدليل.",
        accessShow: "عرض",
        accessHide: "إخفاء",
        logout: "تسجيل الخروج",
        loggedOut: "تم إنهاء الجلسة. يرجى إدخال رمز الوصول مرة أخرى.",
        guideTitle: "هل تعرف كيفية استخدام هذا الوكيل؟",
        guideQuick: "دليل سريع",
        guideLine1: "تظهر الأسئلة واحداً تلو الآخر.",
        guideLine2: "بعد كل إجابة تحصل على تلميح قصير يوجّه الخطوة التالية.",
        guideLine3: "بعد إكمال الخطوات الأربع يتم إنشاء سيناريو قابل للاستخدام فوراً.",
        startAfterGuide: "جيد. سنبدأ من Q1 خطوة بخطوة، مع تلميح قصير بعد كل إجابة لتوضيح الاتجاه التالي.",
        unlockedPlaceholder: "بعد هذا التحقق السريع ستبدأ من Q1.",
        stateMissing: "ستظهر اختياراتك الحالية هنا أثناء الإجابة.",
        checkPlaceholder: "سيظهر هنا فحص سريع للبنية بعد إنشاء السيناريو.",
        outputPlaceholder: "بعد الوصول والإجابة عن الأسئلة الأربعة سترى السيناريو المفصل والتطبيقات حسب الدور.",
        progress1: "Q1 الدور",
        progress2: "Q2 المنطقة",
        progress3: "Q3 المستخدم والسياق",
        progress4: "Q4 الجهاز",
        prev: "السابق",
        next: "التالي",
        build: "إنشاء السيناريو",
        downloadMarkdown: "تنزيل Markdown",
        downloadJson: "تنزيل JSON",
        printPdf: "طباعة / حفظ PDF",
        copySummary: "نسخ الملخص",
        current: "المدخل الحالي",
        check: "فحص البنية",
        output: "مخرجات السيناريو",
        roleQuestion: "Q1. من أي منظور مهني تريد بناء هذا السيناريو؟",
        countryQuestion: "Q2. لأي دولة هذا السيناريو؟",
        personaQuestion: "Q3. ما المستخدم والموقف اللذان تفكر فيهما؟",
        deviceQuestion: "Q4. ما الجهاز الذي يجب أن يكون محور السيناريو؟",
        purposePlaceholder: "مثال: ترغب أسرة ذات دخلين في بدء المساء بشكل أسرع وأكثر راحة بعد العودة إلى المنزل مع الطفل.",
        countryHelper: "قد تختلف الأجهزة المقترحة وزوايا السرد حسب السوق.",
        personaHelper: "أضف العمر ونمط الحياة والموسم والمشكلات المنزلية لجعل السيناريو أكثر إقناعاً.",
        deviceHelper: "اختيار فئة جهاز يجعل السيناريو أكثر مرونة وقابلية للتوسع.",
        roleMissing: "يرجى اختيار المنظور المهني أولاً في Q1.",
        countryMissing: "يرجى اختيار الدولة في Q2.",
        personaMissing: "في Q3، يرجى اختيار نوع المستخدم أو وصف الموقف.",
        allMissing: "يرجى إكمال الأسئلة الأربعة قبل إنشاء السيناريو.",
        downloadFirst: "يرجى إنشاء سيناريو أولاً.",
        summaryState: "ملخص الإدخال",
        detailedScenario: "السيناريو التفصيلي",
        automation: "تدفق الأتمتة",
        facts: "أساس السيناريو",
        confirmed: "معلومات مؤكدة",
        assumptions: "ملاحظات",
        lenses: "الاستخدام حسب الدور",
        effects: "الأثر المتوقع",
        segment: "الجمهور المقترح",
        guide: "البدء",
        evaluation: "التقييم",
        why: "لماذا",
        comparison: "المقارنة",
        note: "ملاحظة",
        roleLens: "منظور الدور",
        executionPoints: "نقاط التنفيذ",
        summary: "الملخص",
        fit: "مناسب",
        review: "يحتاج مراجعة",
        fitCheck: "ملاءمة السيناريو",
        availabilityCheck: "توفر الجهاز",
        executionCheck: "قابلية التنفيذ",
        clarityCheck: "وضوح الرسالة",
        metricCheck: "الارتباط بالنتيجة",
        previewTitle: "أكمل Q1–Q4 واحصل على نتائجك بهذه البنية.",
        prev01Title: "ملخص السيناريو", prev01Desc: "العميل المستهدف وعرض القيمة الأساسي في لمحة.",
        prev02Title: "السيناريو التفصيلي", prev02Desc: "العميل المستهدف والخدمات وبطاقات السيناريو مع المشكلة والحل والفائدة.",
        prev03Title: "رؤية محلية", prev03Desc: "لماذا ينجح هذا السيناريو في هذا السوق — ملاحظة، رؤية، استنتاج.",
        prev04Title: "رسائل تسويقية", prev04Desc: "قارن خيارات النصوص المناسبة للدور المحدد.",
        prev05Title: "فوائد العميل", prev05Desc: "رتّب أولوية المزايا الأكثر إقناعاً للمستخدم.",
        prev06Title: "الجمهور والقبول", prev06Desc: "قدّر مدى القبول والمخاوف والاستقبال قبل التنفيذ.",
        prev07Title: "التوقيت والاتجاه الإبداعي", prev07Desc: "اربط السيناريو بتوقيت الحملة واتجاه السرد.",
        exportPdf: "حفظ PDF", exportPdfDesc: "للاجتماعات ومرفقات البريد",
        exportWord: "حفظ Word", exportWordDesc: "مستند قابل للتعديل للتعاون",
        exportExcel: "حفظ Excel", exportExcelDesc: "جداول بيانات منظمة",
        exportCopy: "نسخ إلى الحافظة", exportCopyDesc: "لصق ومشاركة سريعة",
        outputLabel: "Output", outputTitle: "مخرجات السيناريو",
        outTitle01: "01. العنوان والملخص",
        outTitle02: "02. السيناريو التفصيلي",
        outTitle03: "03. رؤية محلية",
        outTitle04: "04. رسائل تسويقية",
        outTitle05: "05. فوائد العميل",
        outTitle06: "06. الجمهور المستهدف والقبول",
        outTitle07: "07. التوقيت والاتجاه الإبداعي",
        outTitle08: "08. الأجهزة المتاحة ودليل الإعداد",
        outTitle09: "09. تقييم قابلية التسويق والمخاطر",
        outTitle10: "10. حزمة التوسع — التنفيذ وتخطيط مسار التحويل",
        outTitle11: "11. تأمل العلامة التجارية/الذكاء الاصطناعي/الفلسفة",
        guideHeroTitle: "ابنِ سيناريو قابلًا للاستخدام<br>من أربعة مدخلات موجَّهة",
        guideLead: "اختر الأساسيات أولاً. يحوّلها الوكيل إلى سيناريو أدقّ وجاهز للمراجعة.",
        guideInputsTitle: "ما تحدده أولاً",
        guideQ1: "Q1 الدور", guideQ1Desc: "التجزئة أو حملة Dotcom أو تسويق العلامة التجارية",
        guideQ2: "Q2 البلد والمنطقة", guideQ2Desc: "السوق المستهدف مع المدينة أو الولاية أو المنطقة",
        guideQ3: "Q3 العميل المستهدف", guideQ3Desc: "نوع الأسرة والموسم والسياق المعيشي",
        guideQ4: "Q4 الأجهزة والبيئة", guideQ4Desc: "مزيج الأجهزة الأساسية والقيود العملية",
        guideFlowTitle: "إدخال بسيط، نتيجة أوضح",
        guideFlowStep: "سؤال واحد في كل مرة.",
        guideFlowLean: "تظهر الفحوصات الإضافية فقط عند الحاجة.",
        guideFlowClear: "تبقى الافتراضات منفصلة لمراجعة أسرع.",
        guideNote: "إذا كان الأمر واضحاً، اضغط ابدأ أدناه وانتقل إلى Q1. اجعل الإدخال مختصراً — ستكون النتيجة جاهزة للمراجعة.",
        personaTask: "المهمة الرئيسية", personaSuccess: "النتيجة المتوقعة",
        stateRole: "الدور", stateCountry: "البلد", statePersona: "المستخدم المستهدف",
        stateSituation: "الموقف", stateDevice: "الجهاز",
        notSelected: "غير محدد", notEntered: "غير مُدخل",
        guideSessionNote: "تسجيل الخروج ينهي الجلسة الحالية ويعود إلى شاشة رمز الوصول.",
        nudgeNow: "الوضع الحالي", nudgeNeed: "الاحتياج المحتمل", nudgeOpportunity: "الفرصة",
        q3AutoBtn: "تكوين تلقائي حسب الاتجاهات — يختار الذكاء الاصطناعي أفضل شريحة مستهدفة",
        q4AutoBtn: "تكوين تلقائي — يختار الذكاء الاصطناعي الأجهزة المثالية لمنطقتك",
        q4PresetTitle: "إعدادات مسبقة بالنمط", q4DirectTitle: "اختيار مباشر",
        q4DetailSummary: "عرض حسب الفئة", q4SummaryTitle: "ملخص الحالي"
    }
};
